import type { Title } from "./types";

/**
 * Curated catalog. Ratings and vote counts are an IMDb snapshot (approximate,
 * votes in thousands). Blurbs are original one-liners written for this app.
 *
 * Row: [title, year, rating, votesK, kind, genres, country, director/creator,
 *       cast, mood tags, blurb]
 */
type Row = [
  string,
  number,
  number,
  number,
  "m" | "s",
  string,
  string,
  string,
  string,
  string,
  string,
];

const rows: Row[] = [
  // ── Hollywood & English-language films ──────────────────────────────────
  ["The Shawshank Redemption", 1994, 9.3, 3000, "m", "Drama", "US", "Frank Darabont", "Tim Robbins|Morgan Freeman", "inspiring|tearjerker|thoughtful", "Two prisoners build a friendship that outlasts decades behind bars."],
  ["The Godfather", 1972, 9.2, 2100, "m", "Crime|Drama", "US", "Francis Ford Coppola", "Marlon Brando|Al Pacino|James Caan", "dark|epic|slowburn", "A crime dynasty's reluctant son is pulled into the family business."],
  ["The Godfather Part II", 1974, 9.0, 1400, "m", "Crime|Drama", "US", "Francis Ford Coppola", "Al Pacino|Robert De Niro|Robert Duvall", "dark|epic|slowburn", "A son's rise to power mirrors his father's beginnings in old New York."],
  ["The Dark Knight", 2008, 9.0, 3000, "m", "Action|Crime|Drama", "US", "Christopher Nolan", "Christian Bale|Heath Ledger|Aaron Eckhart", "dark|tense|actionpacked|epic", "Batman faces an agent of chaos who wants to watch Gotham burn."],
  ["12 Angry Men", 1957, 9.0, 900, "m", "Crime|Drama", "US", "Sidney Lumet", "Henry Fonda|Lee J. Cobb|Martin Balsam", "tense|thoughtful", "One juror's doubt slowly turns a locked room upside down."],
  ["Schindler's List", 1993, 9.0, 1500, "m", "Biography|Drama|History", "US", "Steven Spielberg", "Liam Neeson|Ben Kingsley|Ralph Fiennes", "tearjerker|epic|thoughtful", "A businessman risks everything to save lives during the Holocaust."],
  ["The Lord of the Rings: The Return of the King", 2003, 9.0, 2000, "m", "Adventure|Drama|Fantasy", "US", "Peter Jackson", "Elijah Wood|Viggo Mortensen|Ian McKellen", "epic|tearjerker|actionpacked", "The final march on Mordor as a king claims his throne."],
  ["The Lord of the Rings: The Fellowship of the Ring", 2001, 8.9, 2100, "m", "Adventure|Drama|Fantasy", "US", "Peter Jackson", "Elijah Wood|Ian McKellen|Orlando Bloom", "epic|cozy", "A humble hobbit sets out to destroy a ring that could doom the world."],
  ["The Lord of the Rings: The Two Towers", 2002, 8.8, 1900, "m", "Adventure|Drama|Fantasy", "US", "Peter Jackson", "Elijah Wood|Viggo Mortensen|Ian McKellen", "epic|actionpacked", "The fellowship scatters as war gathers at Helm's Deep."],
  ["Pulp Fiction", 1994, 8.9, 2300, "m", "Crime|Drama", "US", "Quentin Tarantino", "John Travolta|Uma Thurman|Samuel L. Jackson", "dark|funny", "Hitmen, a boxer and a gangster's wife collide in looping LA stories."],
  ["The Good, the Bad and the Ugly", 1966, 8.8, 850, "m", "Adventure|Western", "IT", "Sergio Leone", "Clint Eastwood|Eli Wallach|Lee Van Cleef", "epic|slowburn", "Three gunslingers race across a war-torn desert for buried gold."],
  ["Forrest Gump", 1994, 8.8, 2300, "m", "Drama|Romance", "US", "Robert Zemeckis", "Tom Hanks|Robin Wright|Gary Sinise", "feelgood|tearjerker|inspiring|nostalgic", "A kind-hearted man drifts through history while loving one woman."],
  ["Fight Club", 1999, 8.8, 2400, "m", "Drama", "US", "David Fincher", "Brad Pitt|Edward Norton|Helena Bonham Carter", "dark|mindbending|twisty", "An insomniac and a soap salesman start an underground club."],
  ["Inception", 2010, 8.8, 2700, "m", "Action|Sci-Fi|Thriller", "US", "Christopher Nolan", "Leonardo DiCaprio|Joseph Gordon-Levitt|Elliot Page", "mindbending|twisty|epic|actionpacked", "A thief who steals secrets through dreams takes one impossible job."],
  ["Star Wars", 1977, 8.6, 1500, "m", "Action|Adventure|Fantasy", "US", "George Lucas", "Mark Hamill|Harrison Ford|Carrie Fisher", "epic|nostalgic|feelgood", "A farm boy joins a rebellion against a galactic empire."],
  ["The Empire Strikes Back", 1980, 8.7, 1400, "m", "Action|Adventure|Fantasy", "US", "Irvin Kershner", "Mark Hamill|Harrison Ford|Carrie Fisher", "epic|nostalgic|twisty", "The rebels scatter as Vader closes in, and a secret changes everything."],
  ["The Matrix", 1999, 8.7, 2200, "m", "Action|Sci-Fi", "US", "Lana Wachowski", "Keanu Reeves|Laurence Fishburne|Carrie-Anne Moss", "mindbending|actionpacked", "A hacker learns the world he knows is a simulation."],
  ["Goodfellas", 1990, 8.7, 1300, "m", "Biography|Crime|Drama", "US", "Martin Scorsese", "Robert De Niro|Ray Liotta|Joe Pesci", "dark|funny", "The rise and fall of a mob associate over three decades."],
  ["One Flew Over the Cuckoo's Nest", 1975, 8.7, 1100, "m", "Drama", "US", "Milos Forman", "Jack Nicholson|Louise Fletcher", "thoughtful|tearjerker", "A rebel shakes up a psychiatric ward ruled by an iron nurse."],
  ["Interstellar", 2014, 8.7, 2300, "m", "Adventure|Drama|Sci-Fi", "US", "Christopher Nolan", "Matthew McConaughey|Anne Hathaway|Jessica Chastain", "epic|tearjerker|mindbending", "Astronauts cross a wormhole to find humanity a new home."],
  ["Se7en", 1995, 8.6, 1800, "m", "Crime|Mystery|Thriller", "US", "David Fincher", "Morgan Freeman|Brad Pitt|Kevin Spacey", "dark|tense|twisty", "Two detectives hunt a killer staging the seven deadly sins."],
  ["The Silence of the Lambs", 1991, 8.6, 1600, "m", "Crime|Thriller|Horror", "US", "Jonathan Demme", "Jodie Foster|Anthony Hopkins", "dark|tense|scary", "A young FBI trainee seeks help from a brilliant cannibal."],
  ["Saving Private Ryan", 1998, 8.6, 1500, "m", "Drama|War", "US", "Steven Spielberg", "Tom Hanks|Matt Damon|Tom Sizemore", "epic|tense|tearjerker", "A squad crosses Normandy to bring one soldier home."],
  ["The Green Mile", 1999, 8.6, 1400, "m", "Crime|Drama|Fantasy", "US", "Frank Darabont", "Tom Hanks|Michael Clarke Duncan|David Morse", "tearjerker|thoughtful", "A death-row guard meets a gentle giant with a miraculous gift."],
  ["Terminator 2: Judgment Day", 1991, 8.6, 1200, "m", "Action|Sci-Fi", "US", "James Cameron", "Arnold Schwarzenegger|Linda Hamilton|Edward Furlong", "actionpacked|nostalgic", "A reprogrammed cyborg protects the boy who will save humanity."],
  ["It's a Wonderful Life", 1946, 8.6, 500, "m", "Drama|Family|Fantasy", "US", "Frank Capra", "James Stewart|Donna Reed", "feelgood|cozy|tearjerker|nostalgic", "An angel shows a desperate man what the world would be without him."],
  ["The Usual Suspects", 1995, 8.5, 1200, "m", "Crime|Mystery|Thriller", "US", "Bryan Singer", "Kevin Spacey|Gabriel Byrne|Benicio Del Toro", "twisty|tense", "Five criminals, one lineup, and a legend no one has seen."],
  ["Léon: The Professional", 1994, 8.5, 1300, "m", "Action|Crime|Drama", "FR", "Luc Besson", "Jean Reno|Natalie Portman|Gary Oldman", "tense|tearjerker|actionpacked", "A solitary hitman takes in a girl whose family was murdered."],
  ["Back to the Future", 1985, 8.5, 1400, "m", "Adventure|Comedy|Sci-Fi", "US", "Robert Zemeckis", "Michael J. Fox|Christopher Lloyd|Lea Thompson", "feelgood|funny|nostalgic|family", "A teen time-travels to 1955 and must make his parents fall in love."],
  ["Gladiator", 2000, 8.5, 1700, "m", "Action|Adventure|Drama", "US", "Ridley Scott", "Russell Crowe|Joaquin Phoenix|Connie Nielsen", "epic|revenge|actionpacked", "A betrayed general fights his way back through the arena."],
  ["The Prestige", 2006, 8.5, 1500, "m", "Drama|Mystery|Sci-Fi", "US", "Christopher Nolan", "Christian Bale|Hugh Jackman|Scarlett Johansson", "twisty|mindbending|dark", "Two rival magicians sacrifice everything for the perfect trick."],
  ["The Departed", 2006, 8.5, 1500, "m", "Crime|Drama|Thriller", "US", "Martin Scorsese", "Leonardo DiCaprio|Matt Damon|Jack Nicholson", "tense|twisty|dark", "A cop undercover in the mob and a mole in the police race to unmask each other."],
  ["Whiplash", 2014, 8.5, 1000, "m", "Drama|Music", "US", "Damien Chazelle", "Miles Teller|J.K. Simmons", "tense|inspiring", "A young drummer and a brutal teacher push each other to the edge."],
  ["Django Unchained", 2012, 8.5, 1700, "m", "Drama|Western", "US", "Quentin Tarantino", "Jamie Foxx|Christoph Waltz|Leonardo DiCaprio", "revenge|actionpacked|funny", "A freed slave and a bounty hunter ride to rescue his wife."],
  ["The Pianist", 2002, 8.5, 900, "m", "Biography|Drama|War", "US", "Roman Polanski", "Adrien Brody|Thomas Kretschmann", "tearjerker|thoughtful", "A pianist survives the destruction of the Warsaw ghetto."],
  ["Casablanca", 1942, 8.5, 600, "m", "Drama|Romance|War", "US", "Michael Curtiz", "Humphrey Bogart|Ingrid Bergman", "romantic|bittersweet|nostalgic", "An old flame walks into a cynical café owner's bar in wartime Morocco."],
  ["Psycho", 1960, 8.5, 750, "m", "Horror|Mystery|Thriller", "US", "Alfred Hitchcock", "Anthony Perkins|Janet Leigh", "scary|tense|twisty", "A runaway checks into a lonely motel run by a nervous young man."],
  ["Rear Window", 1954, 8.5, 550, "m", "Mystery|Thriller", "US", "Alfred Hitchcock", "James Stewart|Grace Kelly", "tense|cozy", "A laid-up photographer suspects his neighbour of murder."],
  ["Alien", 1979, 8.5, 950, "m", "Horror|Sci-Fi", "US", "Ridley Scott", "Sigourney Weaver|Tom Skerritt|John Hurt", "scary|tense", "A space crew picks up a signal and something follows them home."],
  ["Aliens", 1986, 8.4, 750, "m", "Action|Adventure|Sci-Fi", "US", "James Cameron", "Sigourney Weaver|Michael Biehn", "actionpacked|tense|scary", "Ripley returns with marines to the planet that haunted her."],
  ["The Shining", 1980, 8.4, 1100, "m", "Drama|Horror", "US", "Stanley Kubrick", "Jack Nicholson|Shelley Duvall", "scary|dark|slowburn", "A writer's winter as hotel caretaker turns into a nightmare."],
  ["Spider-Man: Into the Spider-Verse", 2018, 8.4, 700, "m", "Animation|Action|Adventure", "US", "Bob Persichetti", "Shameik Moore|Hailee Steinfeld|Mahershala Ali", "feelgood|actionpacked|family|inspiring", "Brooklyn teen Miles Morales meets Spider-People from other dimensions."],
  ["Spider-Man: Across the Spider-Verse", 2023, 8.5, 450, "m", "Animation|Action|Adventure", "US", "Joaquim Dos Santos", "Shameik Moore|Hailee Steinfeld|Oscar Isaac", "actionpacked|epic|feelgood", "Miles is flung across the multiverse and defies its rules."],
  ["Avengers: Endgame", 2019, 8.4, 1300, "m", "Action|Adventure|Sci-Fi", "US", "Anthony Russo", "Robert Downey Jr.|Chris Evans|Scarlett Johansson", "epic|actionpacked|tearjerker", "The surviving heroes make one last stand to undo the snap."],
  ["Avengers: Infinity War", 2018, 8.4, 1200, "m", "Action|Adventure|Sci-Fi", "US", "Anthony Russo", "Robert Downey Jr.|Chris Hemsworth|Josh Brolin", "epic|actionpacked", "Earth's heroes unite against Thanos and his hunt for the Infinity Stones."],
  ["The Avengers", 2012, 8.0, 1500, "m", "Action|Adventure|Sci-Fi", "US", "Joss Whedon", "Robert Downey Jr.|Chris Evans|Scarlett Johansson", "actionpacked|funny", "Earth's mightiest heroes learn to work together."],
  ["Coco", 2017, 8.4, 650, "m", "Animation|Family|Music", "US", "Lee Unkrich", "Anthony Gonzalez|Gael García Bernal", "tearjerker|family|feelgood", "A boy who dreams of music stumbles into the Land of the Dead."],
  ["WALL·E", 2008, 8.4, 1200, "m", "Animation|Adventure|Family", "US", "Andrew Stanton", "Ben Burtt|Elissa Knight", "cozy|feelgood|romantic|family", "A lonely trash-compacting robot falls in love and follows her to space."],
  ["Joker", 2019, 8.4, 1500, "m", "Crime|Drama|Thriller", "US", "Todd Phillips", "Joaquin Phoenix|Robert De Niro|Zazie Beetz", "dark|tense", "A failed comedian's descent in a city that ignores him."],
  ["Inglourious Basterds", 2009, 8.4, 1600, "m", "Adventure|Drama|War", "US", "Quentin Tarantino", "Brad Pitt|Christoph Waltz|Mélanie Laurent", "tense|revenge|funny", "Two plots to bring down Nazi leaders converge on a Paris cinema."],
  ["Memento", 2000, 8.4, 1300, "m", "Mystery|Thriller", "US", "Christopher Nolan", "Guy Pearce|Carrie-Anne Moss", "twisty|mindbending", "A man with no short-term memory hunts his wife's killer."],
  ["Raiders of the Lost Ark", 1981, 8.4, 1000, "m", "Action|Adventure", "US", "Steven Spielberg", "Harrison Ford|Karen Allen", "actionpacked|nostalgic|feelgood", "An archaeologist races the Nazis to the Ark of the Covenant."],
  ["Toy Story", 1995, 8.3, 1100, "m", "Animation|Comedy|Family", "US", "John Lasseter", "Tom Hanks|Tim Allen", "feelgood|family|nostalgic|funny", "A cowboy doll feels replaced by a shiny new space ranger."],
  ["Up", 2009, 8.3, 1150, "m", "Animation|Adventure|Comedy", "US", "Pete Docter", "Ed Asner|Jordan Nagai", "tearjerker|feelgood|family", "A widower ties balloons to his house and flies off on an adventure."],
  ["Good Will Hunting", 1997, 8.3, 1100, "m", "Drama|Romance", "US", "Gus Van Sant", "Matt Damon|Robin Williams|Ben Affleck", "inspiring|tearjerker|thoughtful", "A janitor with a genius mind learns to face his past."],
  ["Eternal Sunshine of the Spotless Mind", 2004, 8.3, 1100, "m", "Drama|Romance|Sci-Fi", "US", "Michel Gondry", "Jim Carrey|Kate Winslet", "romantic|mindbending|bittersweet", "After a breakup, a man has his memories of her erased."],
  ["Oppenheimer", 2023, 8.3, 850, "m", "Biography|Drama|History", "US", "Christopher Nolan", "Cillian Murphy|Emily Blunt|Robert Downey Jr.", "epic|thoughtful|tense", "The physicist who built the atomic bomb faces what he unleashed."],
  ["Dune: Part Two", 2024, 8.5, 650, "m", "Action|Adventure|Sci-Fi", "US", "Denis Villeneuve", "Timothée Chalamet|Zendaya|Rebecca Ferguson", "epic|actionpacked", "Paul unites with the Fremen on a path toward revenge and prophecy."],
  ["Dune", 2021, 8.0, 950, "m", "Action|Adventure|Sci-Fi", "US", "Denis Villeneuve", "Timothée Chalamet|Rebecca Ferguson|Oscar Isaac", "epic|slowburn", "A noble heir is thrust into a war over the universe's most valuable desert."],
  ["Blade Runner 2049", 2017, 8.0, 700, "m", "Drama|Mystery|Sci-Fi", "US", "Denis Villeneuve", "Ryan Gosling|Harrison Ford|Ana de Armas", "slowburn|mindbending", "A replicant hunter uncovers a secret that could break society."],
  ["Blade Runner", 1982, 8.1, 850, "m", "Action|Drama|Sci-Fi", "US", "Ridley Scott", "Harrison Ford|Rutger Hauer|Sean Young", "mindbending|slowburn|dark", "A detective hunts rogue androids in a rain-soaked future LA."],
  ["Arrival", 2016, 7.9, 800, "m", "Drama|Mystery|Sci-Fi", "US", "Denis Villeneuve", "Amy Adams|Jeremy Renner", "thoughtful|mindbending|tearjerker", "A linguist races to decode an alien language before the world panics."],
  ["Prisoners", 2013, 8.1, 850, "m", "Crime|Drama|Mystery", "US", "Denis Villeneuve", "Hugh Jackman|Jake Gyllenhaal|Paul Dano", "dark|tense|twisty", "When two girls vanish, a father takes the law into his own hands."],
  ["Gone Girl", 2014, 8.1, 1100, "m", "Drama|Mystery|Thriller", "US", "David Fincher", "Ben Affleck|Rosamund Pike", "twisty|dark|tense", "A wife disappears and her husband becomes the prime suspect."],
  ["Shutter Island", 2010, 8.2, 1500, "m", "Mystery|Thriller", "US", "Martin Scorsese", "Leonardo DiCaprio|Mark Ruffalo|Ben Kingsley", "twisty|mindbending|tense", "A marshal investigates a disappearance at an island asylum."],
  ["The Wolf of Wall Street", 2013, 8.2, 1600, "m", "Biography|Comedy|Crime", "US", "Martin Scorsese", "Leonardo DiCaprio|Jonah Hill|Margot Robbie", "funny|dark", "A stockbroker's wild rise on fraud, money and excess."],
  ["Titanic", 1997, 7.9, 1300, "m", "Drama|Romance", "US", "James Cameron", "Leonardo DiCaprio|Kate Winslet|Billy Zane", "romantic|tearjerker|epic", "A poor artist and a rich girl fall in love aboard a doomed ship."],
  ["Avatar", 2009, 7.9, 1400, "m", "Action|Adventure|Fantasy", "US", "James Cameron", "Sam Worthington|Zoe Saldaña|Sigourney Weaver", "epic|actionpacked", "A paralysed marine bonds with the people of a lush alien moon."],
  ["Jurassic Park", 1993, 8.2, 1100, "m", "Action|Adventure|Sci-Fi", "US", "Steven Spielberg", "Sam Neill|Laura Dern|Jeff Goldblum", "nostalgic|family|tense", "A theme park of cloned dinosaurs breaks loose."],
  ["E.T. the Extra-Terrestrial", 1982, 7.9, 450, "m", "Adventure|Family|Sci-Fi", "US", "Steven Spielberg", "Henry Thomas|Drew Barrymore", "family|nostalgic|tearjerker|feelgood", "A lonely boy befriends a stranded alien and helps him home."],
  ["Jaws", 1975, 8.1, 650, "m", "Adventure|Thriller", "US", "Steven Spielberg", "Roy Scheider|Robert Shaw|Richard Dreyfuss", "tense|scary|nostalgic", "A beach town is terrorised by a great white shark."],
  ["Catch Me If You Can", 2002, 8.1, 1100, "m", "Biography|Crime|Drama", "US", "Steven Spielberg", "Leonardo DiCaprio|Tom Hanks|Christopher Walken", "feelgood|funny", "A teenage con artist stays one step ahead of the FBI."],
  ["The Truman Show", 1998, 8.2, 1200, "m", "Comedy|Drama", "US", "Peter Weir", "Jim Carrey|Laura Linney|Ed Harris", "thoughtful|feelgood|mindbending", "A man discovers his whole life is a TV show."],
  ["Dead Poets Society", 1989, 8.1, 550, "m", "Comedy|Drama", "US", "Peter Weir", "Robin Williams|Ethan Hawke|Robert Sean Leonard", "inspiring|tearjerker|comingofage", "An unconventional teacher inspires boys to seize the day."],
  ["La La Land", 2016, 8.0, 700, "m", "Comedy|Drama|Music|Romance", "US", "Damien Chazelle", "Ryan Gosling|Emma Stone", "romantic|bittersweet|feelgood", "A pianist and an actress fall in love while chasing their dreams in LA."],
  ["The Notebook", 2004, 7.8, 650, "m", "Drama|Romance", "US", "Nick Cassavetes", "Ryan Gosling|Rachel McAdams", "romantic|tearjerker", "A summer romance becomes a love story told across a lifetime."],
  ["About Time", 2013, 7.8, 400, "m", "Comedy|Drama|Fantasy|Romance", "UK", "Richard Curtis", "Domhnall Gleeson|Rachel McAdams|Bill Nighy", "romantic|feelgood|tearjerker|cozy", "A young man who can time-travel learns what really matters."],
  ["Pride & Prejudice", 2005, 7.8, 330, "m", "Drama|Romance", "UK", "Joe Wright", "Keira Knightley|Matthew Macfadyen", "romantic|cozy|slowburn", "Elizabeth Bennet and Mr Darcy misjudge each other, then fall in love."],
  ["Notting Hill", 1999, 7.2, 350, "m", "Comedy|Drama|Romance", "UK", "Roger Michell", "Julia Roberts|Hugh Grant", "romantic|cozy|funny", "A London bookseller falls for the world's biggest movie star."],
  ["Love Actually", 2003, 7.6, 520, "m", "Comedy|Drama|Romance", "UK", "Richard Curtis", "Hugh Grant|Emma Thompson|Alan Rickman", "cozy|romantic|feelgood", "Ten tangled love stories in London in the weeks before Christmas."],
  ["When Harry Met Sally...", 1989, 7.7, 250, "m", "Comedy|Drama|Romance", "US", "Rob Reiner", "Billy Crystal|Meg Ryan", "romantic|funny|cozy", "Can men and women ever really just be friends?"],
  ["Crazy, Stupid, Love.", 2011, 7.4, 550, "m", "Comedy|Drama|Romance", "US", "Glenn Ficarra", "Steve Carell|Ryan Gosling|Emma Stone", "funny|romantic|feelgood", "A newly single dad gets dating lessons from a smooth-talking ladies' man."],
  ["10 Things I Hate About You", 1999, 7.3, 380, "m", "Comedy|Drama|Romance", "US", "Gil Junger", "Heath Ledger|Julia Stiles|Joseph Gordon-Levitt", "funny|romantic|comingofage|nostalgic", "A rebel is paid to date the school's most prickly girl."],
  ["Before Sunrise", 1995, 8.1, 330, "m", "Drama|Romance", "US", "Richard Linklater", "Ethan Hawke|Julie Delpy", "romantic|slowburn|thoughtful", "Two strangers spend one night walking and talking in Vienna."],
  ["Her", 2013, 8.0, 700, "m", "Drama|Romance|Sci-Fi", "US", "Spike Jonze", "Joaquin Phoenix|Scarlett Johansson|Amy Adams", "thoughtful|romantic|bittersweet", "A lonely writer falls in love with his operating system."],
  ["Past Lives", 2023, 7.8, 150, "m", "Drama|Romance", "US", "Celine Song", "Greta Lee|Teo Yoo|John Magaro", "bittersweet|slowburn|romantic|thoughtful", "Childhood sweethearts reconnect across decades and continents."],
  ["The Grand Budapest Hotel", 2014, 8.1, 900, "m", "Adventure|Comedy|Crime", "US", "Wes Anderson", "Ralph Fiennes|Tony Revolori|Saoirse Ronan", "funny|cozy", "A legendary concierge and his lobby boy are framed for murder."],
  ["Superbad", 2007, 7.6, 650, "m", "Comedy", "US", "Greg Mottola", "Jonah Hill|Michael Cera|Christopher Mintz-Plasse", "funny|comingofage", "Two best friends try to score at one last party before college."],
  ["The Hangover", 2009, 7.7, 850, "m", "Comedy", "US", "Todd Phillips", "Bradley Cooper|Zach Galifianakis|Ed Helms", "funny", "Three friends wake up in Vegas with no memory and no groom."],
  ["Mean Girls", 2004, 7.1, 450, "m", "Comedy", "US", "Mark Waters", "Lindsay Lohan|Rachel McAdams|Tina Fey", "funny|comingofage", "A new girl infiltrates the high school's queen-bee clique."],
  ["Ferris Bueller's Day Off", 1986, 7.8, 400, "m", "Comedy", "US", "John Hughes", "Matthew Broderick|Alan Ruck|Mia Sara", "funny|feelgood|nostalgic", "A charming slacker skips school for the best day ever."],
  ["The Breakfast Club", 1985, 7.8, 450, "m", "Comedy|Drama", "US", "John Hughes", "Emilio Estevez|Molly Ringwald|Judd Nelson", "comingofage|funny|nostalgic", "Five strangers in Saturday detention discover they're not so different."],
  ["Home Alone", 1990, 7.7, 650, "m", "Comedy|Family", "US", "Chris Columbus", "Macaulay Culkin|Joe Pesci|Daniel Stern", "funny|family|cozy|nostalgic", "A boy left behind at Christmas defends his house from burglars."],
  ["The Devil Wears Prada", 2006, 6.9, 500, "m", "Comedy|Drama", "US", "David Frankel", "Meryl Streep|Anne Hathaway|Emily Blunt", "funny|feelgood", "A graduate survives a year assisting a fearsome fashion editor."],
  ["Knives Out", 2019, 7.9, 800, "m", "Comedy|Crime|Mystery", "US", "Rian Johnson", "Daniel Craig|Ana de Armas|Chris Evans", "twisty|funny|cozy", "A detective untangles a rich family's lies after the patriarch dies."],
  ["Paddington 2", 2017, 7.8, 110, "m", "Adventure|Comedy|Family", "UK", "Paul King", "Ben Whishaw|Hugh Grant|Sally Hawkins", "cozy|feelgood|family|funny", "A polite bear is framed for theft and wins over a whole prison."],
  ["Wonka", 2023, 7.0, 220, "m", "Adventure|Comedy|Family", "UK", "Paul King", "Timothée Chalamet|Calah Lane|Hugh Grant", "feelgood|cozy|family", "A young chocolatier with big dreams takes on a chocolate cartel."],
  ["Everything Everywhere All at Once", 2022, 7.8, 600, "m", "Action|Adventure|Comedy", "US", "Daniel Kwan", "Michelle Yeoh|Ke Huy Quan|Jamie Lee Curtis", "mindbending|funny|tearjerker", "A laundromat owner must connect with her multiverse selves."],
  ["Mad Max: Fury Road", 2015, 8.1, 1100, "m", "Action|Adventure|Sci-Fi", "AU", "George Miller", "Tom Hardy|Charlize Theron|Nicholas Hoult", "actionpacked|epic", "A wasteland drifter and a rebel warrior flee a tyrant in a war rig."],
  ["John Wick", 2014, 7.4, 750, "m", "Action|Thriller", "US", "Chad Stahelski", "Keanu Reeves|Michael Nyqvist|Willem Dafoe", "actionpacked|revenge", "A retired hitman returns for the people who killed his dog."],
  ["Top Gun: Maverick", 2022, 8.2, 750, "m", "Action|Drama", "US", "Joseph Kosinski", "Tom Cruise|Miles Teller|Jennifer Connelly", "actionpacked|feelgood|inspiring", "A legendary pilot trains a new squad for an impossible mission."],
  ["Mission: Impossible - Fallout", 2018, 7.7, 400, "m", "Action|Adventure|Thriller", "US", "Christopher McQuarrie", "Tom Cruise|Henry Cavill|Rebecca Ferguson", "actionpacked|tense", "Ethan Hunt races to stop a nuclear plot after a mission goes wrong."],
  ["Die Hard", 1988, 8.2, 950, "m", "Action|Thriller", "US", "John McTiernan", "Bruce Willis|Alan Rickman", "actionpacked|nostalgic|funny", "A cop takes on terrorists in an LA skyscraper on Christmas Eve."],
  ["Kill Bill: Vol. 1", 2003, 8.2, 1200, "m", "Action|Crime|Thriller", "US", "Quentin Tarantino", "Uma Thurman|Lucy Liu|Vivica A. Fox", "revenge|actionpacked", "A bride wakes from a coma and hunts the squad that betrayed her."],
  ["No Country for Old Men", 2007, 8.2, 1100, "m", "Crime|Drama|Thriller", "US", "Joel Coen", "Javier Bardem|Josh Brolin|Tommy Lee Jones", "tense|dark|slowburn", "A hunter finds drug money and is stalked by a relentless killer."],
  ["The Social Network", 2010, 7.8, 800, "m", "Biography|Drama", "US", "David Fincher", "Jesse Eisenberg|Andrew Garfield|Justin Timberlake", "thoughtful|tense", "The founding of Facebook and the friendships it cost."],
  ["Get Out", 2017, 7.8, 700, "m", "Horror|Mystery|Thriller", "US", "Jordan Peele", "Daniel Kaluuya|Allison Williams", "scary|twisty|tense", "A weekend meeting his girlfriend's parents turns sinister."],
  ["Hereditary", 2018, 7.3, 400, "m", "Drama|Horror|Mystery", "US", "Ari Aster", "Toni Collette|Alex Wolff|Milly Shapiro", "scary|dark", "After a funeral, a family unravels under a terrifying inheritance."],
  ["The Conjuring", 2013, 7.5, 550, "m", "Horror|Mystery|Thriller", "US", "James Wan", "Vera Farmiga|Patrick Wilson", "scary|tense", "Paranormal investigators help a family terrorised in their farmhouse."],
  ["A Quiet Place", 2018, 7.5, 600, "m", "Drama|Horror|Sci-Fi", "US", "John Krasinski", "Emily Blunt|John Krasinski|Millicent Simmonds", "scary|tense", "A family survives in silence from creatures that hunt by sound."],
  ["It", 2017, 7.3, 650, "m", "Horror", "US", "Andy Muschietti", "Bill Skarsgård|Jaeden Martell|Finn Wolfhard", "scary|comingofage", "A band of misfit kids faces a shape-shifting clown."],
  ["The Exorcist", 1973, 8.1, 450, "m", "Horror", "US", "William Friedkin", "Ellen Burstyn|Linda Blair|Max von Sydow", "scary|dark", "A mother seeks help when her daughter is possessed."],
  ["The Sixth Sense", 1999, 8.2, 1100, "m", "Drama|Mystery|Thriller", "US", "M. Night Shyamalan", "Bruce Willis|Haley Joel Osment|Toni Collette", "twisty|scary|tearjerker", "A child psychologist treats a boy who sees dead people."],
  ["The Others", 2001, 7.6, 400, "m", "Horror|Mystery", "US", "Alejandro Amenábar", "Nicole Kidman|Fionnula Flanagan", "scary|twisty|slowburn", "A mother in a dark manor believes her house is haunted."],
  ["Gravity", 2013, 7.7, 900, "m", "Drama|Sci-Fi|Thriller", "US", "Alfonso Cuarón", "Sandra Bullock|George Clooney", "tense|inspiring", "Two astronauts are stranded after debris destroys their shuttle."],
  ["The Martian", 2015, 8.0, 950, "m", "Adventure|Drama|Sci-Fi", "US", "Ridley Scott", "Matt Damon|Jessica Chastain|Chiwetel Ejiofor", "feelgood|funny|inspiring", "A stranded astronaut science-s his way to survival on Mars."],
  ["Edge of Tomorrow", 2014, 7.9, 750, "m", "Action|Sci-Fi", "US", "Doug Liman", "Tom Cruise|Emily Blunt", "actionpacked|mindbending|funny", "A soldier relives the same alien battle every time he dies."],
  ["Tenet", 2020, 7.3, 600, "m", "Action|Sci-Fi|Thriller", "US", "Christopher Nolan", "John David Washington|Robert Pattinson|Elizabeth Debicki", "mindbending|actionpacked", "A secret agent manipulates the flow of time to prevent World War III."],
  ["The Batman", 2022, 7.8, 850, "m", "Action|Crime|Drama", "US", "Matt Reeves", "Robert Pattinson|Zoë Kravitz|Paul Dano", "dark|tense|slowburn", "A young Batman hunts a serial killer leaving riddles across Gotham."],
  ["Guardians of the Galaxy", 2014, 8.0, 1300, "m", "Action|Adventure|Comedy", "US", "James Gunn", "Chris Pratt|Zoe Saldaña|Dave Bautista", "funny|actionpacked|feelgood", "A band of misfit outlaws must save the galaxy, set to a killer mixtape."],
  ["Spider-Man: No Way Home", 2021, 8.2, 900, "m", "Action|Adventure|Fantasy", "US", "Jon Watts", "Tom Holland|Zendaya|Benedict Cumberbatch", "actionpacked|feelgood|tearjerker", "A spell gone wrong pulls villains from other universes into Peter's world."],
  ["Iron Man", 2008, 7.9, 1200, "m", "Action|Adventure|Sci-Fi", "US", "Jon Favreau", "Robert Downey Jr.|Gwyneth Paltrow|Terrence Howard", "actionpacked|funny", "A billionaire weapons maker builds a suit and changes course."],
  ["Logan", 2017, 8.1, 850, "m", "Action|Drama|Sci-Fi", "US", "James Mangold", "Hugh Jackman|Patrick Stewart|Dafne Keen", "dark|tearjerker|actionpacked", "An ageing Wolverine protects a girl with powers like his own."],
  ["Deadpool", 2016, 8.0, 1200, "m", "Action|Comedy", "US", "Tim Miller", "Ryan Reynolds|Morena Baccarin", "funny|actionpacked", "A wisecracking mercenary seeks revenge on the man who scarred him."],
  ["Free Guy", 2021, 7.1, 420, "m", "Action|Comedy|Sci-Fi", "US", "Shawn Levy", "Ryan Reynolds|Jodie Comer", "funny|feelgood", "A background character in a video game decides to become the hero."],
  ["Ford v Ferrari", 2019, 8.1, 470, "m", "Action|Biography|Drama", "US", "James Mangold", "Matt Damon|Christian Bale", "inspiring|actionpacked", "An engineer and a driver build a car to beat Ferrari at Le Mans."],
  ["Harry Potter and the Sorcerer's Stone", 2001, 7.6, 900, "m", "Adventure|Family|Fantasy", "UK", "Chris Columbus", "Daniel Radcliffe|Emma Watson|Rupert Grint", "cozy|family|nostalgic", "An orphan learns he's a wizard and heads to Hogwarts."],
  ["Harry Potter and the Prisoner of Azkaban", 2004, 7.9, 700, "m", "Adventure|Family|Fantasy", "UK", "Alfonso Cuarón", "Daniel Radcliffe|Emma Watson|Rupert Grint", "cozy|family|twisty", "An escaped prisoner seems to be hunting Harry."],
  ["Harry Potter and the Deathly Hallows: Part 2", 2011, 8.1, 950, "m", "Adventure|Family|Fantasy", "UK", "David Yates", "Daniel Radcliffe|Emma Watson|Rupert Grint", "epic|tearjerker|actionpacked", "The final battle for Hogwarts."],
  ["Pirates of the Caribbean: The Curse of the Black Pearl", 2003, 8.1, 1200, "m", "Action|Adventure|Fantasy", "US", "Gore Verbinski", "Johnny Depp|Orlando Bloom|Keira Knightley", "funny|actionpacked|feelgood", "A blacksmith teams up with an eccentric pirate to rescue a governor's daughter."],
  ["The Princess Bride", 1987, 8.0, 450, "m", "Adventure|Family|Fantasy", "US", "Rob Reiner", "Cary Elwes|Robin Wright|Mandy Patinkin", "cozy|funny|romantic|nostalgic", "A farmhand-turned-pirate sets out to rescue his true love."],
  ["Shrek", 2001, 7.9, 750, "m", "Animation|Adventure|Comedy", "US", "Andrew Adamson", "Mike Myers|Eddie Murphy|Cameron Diaz", "funny|family|feelgood", "A grumpy ogre rescues a princess to get his swamp back."],
  ["Finding Nemo", 2003, 8.2, 1100, "m", "Animation|Adventure|Comedy", "US", "Andrew Stanton", "Albert Brooks|Ellen DeGeneres", "family|feelgood|funny", "A timid clownfish crosses the ocean to find his son."],
  ["Ratatouille", 2007, 8.1, 850, "m", "Animation|Adventure|Comedy", "US", "Brad Bird", "Patton Oswalt|Lou Romano", "cozy|feelgood|family", "A rat with a gift for cooking teams up with a hapless kitchen boy in Paris."],
  ["The Incredibles", 2004, 8.0, 800, "m", "Animation|Action|Adventure", "US", "Brad Bird", "Craig T. Nelson|Holly Hunter|Samuel L. Jackson", "family|actionpacked|funny", "A family of undercover superheroes is pulled back into action."],
  ["The Iron Giant", 1999, 8.1, 230, "m", "Animation|Action|Adventure", "US", "Brad Bird", "Eli Marienthal|Vin Diesel|Jennifer Aniston", "tearjerker|family|nostalgic", "A boy befriends a giant robot from outer space."],
  ["Monsters, Inc.", 2001, 8.1, 1000, "m", "Animation|Adventure|Comedy", "US", "Pete Docter", "John Goodman|Billy Crystal", "funny|family|cozy", "Two monsters who scare kids for energy find a little girl in their world."],
  ["Inside Out", 2015, 8.1, 800, "m", "Animation|Adventure|Comedy", "US", "Pete Docter", "Amy Poehler|Phyllis Smith|Bill Hader", "feelgood|family|tearjerker", "A girl's emotions get lost inside her head as her life changes."],
  ["Inside Out 2", 2024, 7.6, 250, "m", "Animation|Adventure|Comedy", "US", "Kelsey Mann", "Amy Poehler|Maya Hawke", "feelgood|family|funny", "New emotions, led by Anxiety, move into a teenager's mind."],
  ["Soul", 2020, 8.0, 380, "m", "Animation|Adventure|Comedy", "US", "Pete Docter", "Jamie Foxx|Tina Fey", "thoughtful|feelgood", "A jazz teacher's soul gets separated from his body on his big day."],
  ["How to Train Your Dragon", 2010, 8.1, 800, "m", "Animation|Action|Adventure", "US", "Dean DeBlois", "Jay Baruchel|Gerard Butler|America Ferrera", "family|feelgood|epic", "A Viking teen befriends the dragon he was meant to kill."],
  ["Zootopia", 2016, 8.0, 550, "m", "Animation|Adventure|Comedy", "US", "Byron Howard", "Ginnifer Goodwin|Jason Bateman", "funny|family|twisty", "A rookie bunny cop and a con-artist fox crack a conspiracy."],
  ["Encanto", 2021, 7.2, 280, "m", "Animation|Comedy|Family", "US", "Byron Howard", "Stephanie Beatriz|María Cecilia Botero", "family|feelgood", "The only member of a magical family without powers tries to save it."],
  ["Frozen", 2013, 7.4, 700, "m", "Animation|Adventure|Comedy", "US", "Chris Buck", "Kristen Bell|Idina Menzel|Josh Gad", "family|feelgood", "A fearless princess sets out to find her sister, whose powers froze the kingdom."],
  ["The Lion King", 1994, 8.5, 1200, "m", "Animation|Adventure|Drama", "US", "Roger Allers", "Matthew Broderick|Jeremy Irons|James Earl Jones", "family|tearjerker|nostalgic|epic", "A lion cub flees his kingdom and must return to claim it."],
  ["Aladdin", 1992, 8.0, 470, "m", "Animation|Adventure|Comedy", "US", "Ron Clements", "Robin Williams|Scott Weinger|Linda Larkin", "family|funny|nostalgic|romantic", "A street kid finds a magic lamp and a genie with big personality."],
  ["Beauty and the Beast", 1991, 8.0, 480, "m", "Animation|Family|Fantasy", "US", "Gary Trousdale", "Paige O'Hara|Robby Benson", "romantic|family|cozy|nostalgic", "A bookish young woman sees the heart of a cursed prince."],
  ["Klaus", 2019, 8.2, 190, "m", "Animation|Adventure|Comedy", "ES", "Sergio Pablos", "Jason Schwartzman|J.K. Simmons|Rashida Jones", "cozy|feelgood|family|tearjerker", "A spoiled postman and a reclusive toymaker spark a Christmas legend."],
  ["Poor Things", 2023, 7.8, 300, "m", "Comedy|Drama|Romance", "UK", "Yorgos Lanthimos", "Emma Stone|Mark Ruffalo|Willem Dafoe", "funny|mindbending", "A woman brought back to life sets off to discover the world."],
  ["Barbie", 2023, 6.8, 600, "m", "Adventure|Comedy|Fantasy", "US", "Greta Gerwig", "Margot Robbie|Ryan Gosling|America Ferrera", "funny|feelgood|thoughtful", "Barbie leaves her perfect world and discovers the real one."],
  ["Little Women", 2019, 7.8, 230, "m", "Drama|Romance", "US", "Greta Gerwig", "Saoirse Ronan|Florence Pugh|Timothée Chalamet", "cozy|feelgood|comingofage|tearjerker", "Four sisters grow up and chase their own lives after the Civil War."],
  ["Lady Bird", 2017, 7.4, 330, "m", "Comedy|Drama", "US", "Greta Gerwig", "Saoirse Ronan|Laurie Metcalf", "comingofage|funny|bittersweet", "A headstrong teenager and her mother clash in her final year of school."],
  ["The Perks of Being a Wallflower", 2012, 7.9, 560, "m", "Drama|Romance", "US", "Stephen Chbosky", "Logan Lerman|Emma Watson|Ezra Miller", "comingofage|tearjerker", "A shy freshman is taken under the wing of two free-spirited seniors."],
  ["Wonder", 2017, 7.9, 190, "m", "Drama|Family", "US", "Stephen Chbosky", "Jacob Tremblay|Julia Roberts|Owen Wilson", "feelgood|tearjerker|family|inspiring", "A boy with a facial difference starts school for the first time."],
  ["Call Me by Your Name", 2017, 7.8, 300, "m", "Drama|Romance", "IT", "Luca Guadagnino", "Timothée Chalamet|Armie Hammer|Michael Stuhlbarg", "romantic|bittersweet|slowburn", "A summer romance blooms in the Italian countryside."],
  ["Little Miss Sunshine", 2006, 7.8, 500, "m", "Comedy|Drama", "US", "Jonathan Dayton", "Abigail Breslin|Steve Carell|Toni Collette", "feelgood|funny", "A dysfunctional family road-trips to a kids' beauty pageant."],
  ["The Secret Life of Walter Mitty", 2013, 7.3, 350, "m", "Adventure|Comedy|Drama", "US", "Ben Stiller", "Ben Stiller|Kristen Wiig", "feelgood|inspiring", "A daydreamer sets off on a real-world adventure to find a missing photo."],
  ["Chef", 2014, 7.3, 220, "m", "Adventure|Comedy|Drama", "US", "Jon Favreau", "Jon Favreau|Sofía Vergara|John Leguizamo", "cozy|feelgood", "A chef quits his job, starts a food truck and reconnects with his son."],
  ["The Holiday", 2006, 6.9, 300, "m", "Comedy|Romance", "US", "Nancy Meyers", "Cameron Diaz|Kate Winslet|Jude Law", "cozy|romantic", "Two heartbroken women swap homes for Christmas."],
  ["Groundhog Day", 1993, 8.0, 700, "m", "Comedy|Drama|Fantasy", "US", "Harold Ramis", "Bill Murray|Andie MacDowell", "funny|feelgood|mindbending", "A cynical weatherman relives the same day over and over."],
  ["The Terminal", 2004, 7.4, 500, "m", "Comedy|Drama|Romance", "US", "Steven Spielberg", "Tom Hanks|Catherine Zeta-Jones", "feelgood|cozy", "A traveller is stranded living inside a New York airport."],
  ["Cast Away", 2000, 7.8, 650, "m", "Adventure|Drama|Romance", "US", "Robert Zemeckis", "Tom Hanks|Helen Hunt", "tearjerker|inspiring", "A FedEx engineer is stranded alone on a deserted island."],
  ["A Beautiful Mind", 2001, 8.2, 1000, "m", "Biography|Drama", "US", "Ron Howard", "Russell Crowe|Jennifer Connelly|Ed Harris", "inspiring|twisty|tearjerker", "A brilliant mathematician battles schizophrenia."],
  ["Slumdog Millionaire", 2008, 8.0, 900, "m", "Crime|Drama|Romance", "UK", "Danny Boyle", "Dev Patel|Freida Pinto|Anil Kapoor", "inspiring|romantic|tense", "A Mumbai teen is one question away from winning a game show."],
  ["Life of Pi", 2012, 7.9, 650, "m", "Adventure|Drama|Fantasy", "US", "Ang Lee", "Suraj Sharma|Irrfan Khan", "thoughtful|epic|inspiring", "A boy is lost at sea on a lifeboat with a Bengal tiger."],
  ["1917", 2019, 8.2, 700, "m", "Action|Drama|War", "UK", "Sam Mendes", "George MacKay|Dean-Charles Chapman", "tense|epic", "Two soldiers race across no-man's-land to deliver a message."],
  ["Dunkirk", 2017, 7.8, 750, "m", "Action|Drama|History", "UK", "Christopher Nolan", "Fionn Whitehead|Tom Hardy|Cillian Murphy", "tense|epic", "Soldiers trapped on a beach await rescue by land, sea and air."],
  ["Hacksaw Ridge", 2016, 8.1, 600, "m", "Biography|Drama|War", "US", "Mel Gibson", "Andrew Garfield|Vince Vaughn", "inspiring|tense", "A medic who refuses to carry a gun saves 75 men in battle."],
  ["Braveheart", 1995, 8.3, 1100, "m", "Biography|Drama|War", "US", "Mel Gibson", "Mel Gibson|Sophie Marceau", "epic|revenge", "A Scottish warrior leads a rebellion against English rule."],
  ["Heat", 1995, 8.3, 750, "m", "Action|Crime|Drama", "US", "Michael Mann", "Al Pacino|Robert De Niro|Val Kilmer", "tense|slowburn", "A detective and a master thief circle each other across LA."],
  ["Scarface", 1983, 8.3, 950, "m", "Crime|Drama", "US", "Brian De Palma", "Al Pacino|Michelle Pfeiffer", "dark", "A Cuban immigrant builds a cocaine empire in Miami."],
  ["Taxi Driver", 1976, 8.2, 950, "m", "Crime|Drama", "US", "Martin Scorsese", "Robert De Niro|Jodie Foster", "dark|slowburn", "A lonely cab driver spirals in a decaying New York."],
  ["Killers of the Flower Moon", 2023, 7.6, 250, "m", "Crime|Drama|History", "US", "Martin Scorsese", "Leonardo DiCaprio|Lily Gladstone|Robert De Niro", "slowburn|dark", "Osage Nation members are murdered for their oil wealth."],
  ["There Will Be Blood", 2007, 8.2, 650, "m", "Drama", "US", "Paul Thomas Anderson", "Daniel Day-Lewis|Paul Dano", "dark|slowburn", "An oilman's ambition consumes everything around him."],
  ["2001: A Space Odyssey", 1968, 8.3, 750, "m", "Adventure|Sci-Fi", "US", "Stanley Kubrick", "Keir Dullea|Gary Lockwood", "mindbending|slowburn|epic", "A mysterious monolith guides humanity from apes to the stars."],
  ["Ex Machina", 2014, 7.7, 600, "m", "Drama|Sci-Fi|Thriller", "UK", "Alex Garland", "Domhnall Gleeson|Alicia Vikander|Oscar Isaac", "mindbending|tense|twisty", "A programmer tests whether an AI is truly conscious."],
  ["Predestination", 2014, 7.4, 300, "m", "Action|Drama|Mystery", "AU", "Michael Spierig", "Ethan Hawke|Sarah Snook", "mindbending|twisty", "A time-travelling agent chases the one criminal who always escapes."],
  ["Coherence", 2013, 7.2, 160, "m", "Drama|Mystery|Sci-Fi", "US", "James Ward Byrkit", "Emily Baldoni|Maury Sterling", "mindbending|twisty|tense", "A dinner party unravels the night a comet passes overhead."],
  ["Donnie Darko", 2001, 8.0, 850, "m", "Drama|Mystery|Sci-Fi", "US", "Richard Kelly", "Jake Gyllenhaal|Jena Malone", "mindbending|dark", "A troubled teen is told the world will end in 28 days."],
  ["Black Swan", 2010, 8.0, 800, "m", "Drama|Thriller", "US", "Darren Aronofsky", "Natalie Portman|Mila Kunis", "dark|mindbending|tense", "A ballerina's quest for perfection fractures her mind."],
  ["Nightcrawler", 2014, 7.8, 600, "m", "Crime|Drama|Thriller", "US", "Dan Gilroy", "Jake Gyllenhaal|Rene Russo", "dark|tense", "A driven loner muscles into LA's crime-scene news business."],
  ["Zodiac", 2007, 7.7, 650, "m", "Crime|Drama|Mystery", "US", "David Fincher", "Jake Gyllenhaal|Robert Downey Jr.|Mark Ruffalo", "slowburn|tense", "A cartoonist becomes obsessed with an uncatchable serial killer."],
  ["Sicario", 2015, 7.6, 450, "m", "Action|Crime|Drama", "US", "Denis Villeneuve", "Emily Blunt|Benicio Del Toro|Josh Brolin", "tense|dark", "An idealistic FBI agent is drawn into the war on cartels."],
  ["Baby Driver", 2017, 7.5, 600, "m", "Action|Crime|Music", "US", "Edgar Wright", "Ansel Elgort|Lily James|Jon Hamm", "actionpacked|funny|romantic", "A getaway driver plans one last heist to his own soundtrack."],
  ["Hot Fuzz", 2007, 7.8, 550, "m", "Action|Comedy|Mystery", "UK", "Edgar Wright", "Simon Pegg|Nick Frost", "funny|twisty", "A top London cop is reassigned to a suspiciously perfect village."],
  ["Shaun of the Dead", 2004, 7.9, 600, "m", "Comedy|Horror", "UK", "Edgar Wright", "Simon Pegg|Nick Frost", "funny|scary", "A slacker tries to save his mum and his ex from a zombie outbreak."],
  ["Fargo", 1996, 8.1, 720, "m", "Crime|Thriller", "US", "Joel Coen", "Frances McDormand|William H. Macy|Steve Buscemi", "funny|dark", "A pregnant police chief investigates a botched kidnapping."],
  ["The Big Lebowski", 1998, 8.1, 850, "m", "Comedy|Crime", "US", "Joel Coen", "Jeff Bridges|John Goodman|Julianne Moore", "funny", "A laid-back slacker is mistaken for a millionaire."],
  ["The Big Short", 2015, 7.8, 480, "m", "Biography|Comedy|Drama", "US", "Adam McKay", "Christian Bale|Steve Carell|Ryan Gosling", "funny|thoughtful", "Outsiders bet against the housing market before the 2008 crash."],
  ["Spotlight", 2015, 8.1, 500, "m", "Biography|Crime|Drama", "US", "Tom McCarthy", "Mark Ruffalo|Michael Keaton|Rachel McAdams", "thoughtful|tense", "Journalists uncover a cover-up inside the Boston archdiocese."],
  ["Rocky", 1976, 8.1, 650, "m", "Drama|Sport", "US", "John G. Avildsen", "Sylvester Stallone|Talia Shire", "inspiring|feelgood|romantic", "A small-time boxer gets a shot at the heavyweight title."],
  ["The Pursuit of Happyness", 2006, 8.0, 600, "m", "Biography|Drama", "US", "Gabriele Muccino", "Will Smith|Jaden Smith", "inspiring|tearjerker", "A struggling salesman fights homelessness while raising his son."],
  ["Hidden Figures", 2016, 7.8, 250, "m", "Biography|Drama|History", "US", "Theodore Melfi", "Taraji P. Henson|Octavia Spencer|Janelle Monáe", "inspiring|feelgood", "Three Black women mathematicians power NASA's space race."],
  ["The Help", 2011, 8.1, 500, "m", "Drama", "US", "Tate Taylor", "Viola Davis|Emma Stone|Octavia Spencer", "inspiring|tearjerker|funny", "A young writer records the stories of Black maids in 1960s Mississippi."],
  ["Green Book", 2018, 8.2, 570, "m", "Biography|Comedy|Drama", "US", "Peter Farrelly", "Viggo Mortensen|Mahershala Ali", "feelgood|funny|inspiring", "A bouncer drives a pianist through the segregated South."],
  ["The Blind Side", 2009, 7.6, 350, "m", "Biography|Drama|Sport", "US", "John Lee Hancock", "Sandra Bullock|Quinton Aaron", "inspiring|feelgood", "A family takes in a homeless teen who becomes a football star."],
  ["Moneyball", 2011, 7.6, 450, "m", "Biography|Drama|Sport", "US", "Bennett Miller", "Brad Pitt|Jonah Hill", "inspiring|thoughtful", "A baseball manager rebuilds his team using data."],
  ["Bohemian Rhapsody", 2018, 7.9, 600, "m", "Biography|Drama|Music", "US", "Bryan Singer", "Rami Malek|Lucy Boynton|Gwilym Lee", "feelgood|inspiring", "The story of Queen and Freddie Mercury, up to Live Aid."],
  ["The Greatest Showman", 2017, 7.5, 340, "m", "Biography|Drama|Music", "US", "Michael Gracey", "Hugh Jackman|Zac Efron|Zendaya", "feelgood|romantic|inspiring", "P.T. Barnum dreams up a spectacle that becomes the circus."],
  ["Mamma Mia!", 2008, 6.5, 270, "m", "Comedy|Music|Romance", "US", "Phyllida Lloyd", "Meryl Streep|Amanda Seyfried|Pierce Brosnan", "feelgood|funny|cozy", "A bride-to-be invites three possible fathers to her Greek wedding."],
  ["Sing Street", 2016, 7.9, 100, "m", "Comedy|Drama|Music", "IE", "John Carney", "Ferdia Walsh-Peelo|Lucy Boynton", "feelgood|comingofage|romantic", "A Dublin teen starts a band to impress a mysterious girl."],
  ["Begin Again", 2013, 7.4, 170, "m", "Comedy|Drama|Music", "US", "John Carney", "Keira Knightley|Mark Ruffalo|Adam Levine", "feelgood|cozy", "A heartbroken songwriter and a washed-up producer record an album on NYC streets."],
  ["School of Rock", 2003, 7.2, 300, "m", "Comedy|Music", "US", "Richard Linklater", "Jack Black|Joan Cusack", "funny|feelgood|family", "A failed rocker poses as a teacher and forms a band with his class."],
  ["CODA", 2021, 8.0, 170, "m", "Comedy|Drama|Music", "US", "Sian Heder", "Emilia Jones|Troy Kotsur|Marlee Matlin", "feelgood|tearjerker|comingofage", "The only hearing member of a deaf family discovers her voice."],
  ["The Fault in Our Stars", 2014, 7.7, 400, "m", "Drama|Romance", "US", "Josh Boone", "Shailene Woodley|Ansel Elgort", "tearjerker|romantic|comingofage", "Two teens with cancer fall in love and take a trip to Amsterdam."],
  ["A Walk to Remember", 2002, 7.3, 220, "m", "Drama|Romance", "US", "Adam Shankman", "Mandy Moore|Shane West", "tearjerker|romantic", "A rebellious teen falls for the minister's quiet daughter."],
  ["Me Before You", 2016, 7.4, 280, "m", "Drama|Romance", "UK", "Thea Sharrock", "Emilia Clarke|Sam Claflin", "tearjerker|romantic", "A cheerful carer changes a paralysed man's world, and he changes hers."],
  ["Marriage Story", 2019, 7.9, 340, "m", "Comedy|Drama|Romance", "US", "Noah Baumbach", "Adam Driver|Scarlett Johansson|Laura Dern", "tearjerker|thoughtful", "A couple's coast-to-coast divorce tests what love leaves behind."],
  ["Manchester by the Sea", 2016, 7.8, 330, "m", "Drama", "US", "Kenneth Lonergan", "Casey Affleck|Michelle Williams|Lucas Hedges", "tearjerker|slowburn", "A grieving man becomes guardian to his teenage nephew."],
  ["Room", 2015, 8.1, 450, "m", "Drama|Thriller", "US", "Lenny Abrahamson", "Brie Larson|Jacob Tremblay", "tearjerker|tense|inspiring", "A mother and son held captive plan their escape."],
  ["Hachi: A Dog's Tale", 2009, 8.1, 300, "m", "Biography|Drama|Family", "US", "Lasse Hallström", "Richard Gere|Joan Allen", "tearjerker|family", "A loyal dog waits for his owner at the station every day."],
  ["Lost in Translation", 2003, 7.7, 500, "m", "Comedy|Drama", "US", "Sofia Coppola", "Bill Murray|Scarlett Johansson", "bittersweet|slowburn|thoughtful", "Two lonely Americans form an unlikely bond in Tokyo."],
  ["Crazy Rich Asians", 2018, 6.9, 200, "m", "Comedy|Drama|Romance", "US", "Jon M. Chu", "Constance Wu|Henry Golding|Michelle Yeoh", "romantic|funny|feelgood", "A professor discovers her boyfriend's family is absurdly rich."],
  ["To All the Boys I've Loved Before", 2018, 7.0, 120, "m", "Comedy|Drama|Romance", "US", "Susan Johnson", "Lana Condor|Noah Centineo", "romantic|cozy|comingofage", "A teen's secret love letters are mailed to all her crushes."],
  ["Jab Tak Hai Jaan", 2012, 6.7, 55, "m", "Drama|Romance", "IN", "Yash Chopra", "Shah Rukh Khan|Katrina Kaif|Anushka Sharma", "romantic|tearjerker", "A bomb-disposal expert's past love story resurfaces."],
  ["The Sound of Music", 1965, 8.1, 270, "m", "Biography|Drama|Family|Music", "US", "Robert Wise", "Julie Andrews|Christopher Plummer", "feelgood|family|nostalgic|cozy", "A spirited governess brings music to a strict captain's household."],
  ["Singin' in the Rain", 1952, 8.3, 260, "m", "Comedy|Music|Romance", "US", "Gene Kelly", "Gene Kelly|Debbie Reynolds|Donald O'Connor", "feelgood|nostalgic|funny", "Hollywood stars stumble through the switch to talking pictures."],
  ["Roman Holiday", 1953, 8.0, 150, "m", "Comedy|Romance", "US", "William Wyler", "Audrey Hepburn|Gregory Peck", "romantic|cozy|bittersweet", "A runaway princess spends one magical day in Rome."],
  ["Breakfast at Tiffany's", 1961, 7.6, 200, "m", "Comedy|Drama|Romance", "US", "Blake Edwards", "Audrey Hepburn|George Peppard", "romantic|cozy|nostalgic", "A free-spirited New Yorker charms her neighbour, a struggling writer."],
  ["Stand by Me", 1986, 8.1, 450, "m", "Adventure|Drama", "US", "Rob Reiner", "Wil Wheaton|River Phoenix|Corey Feldman", "comingofage|nostalgic|bittersweet", "Four boys hike to find a body in their last summer together."],
  ["Dirty Dancing", 1987, 7.0, 250, "m", "Drama|Music|Romance", "US", "Emile Ardolino", "Patrick Swayze|Jennifer Grey", "romantic|nostalgic|feelgood", "A sheltered teen falls for a resort's dance instructor."],
  ["Pretty Woman", 1990, 7.1, 330, "m", "Comedy|Romance", "US", "Garry Marshall", "Julia Roberts|Richard Gere", "romantic|funny|feelgood", "A businessman hires a vivacious woman for a week and falls for her."],
  ["Mrs. Doubtfire", 1993, 7.1, 300, "m", "Comedy|Drama|Family", "US", "Chris Columbus", "Robin Williams|Sally Field|Pierce Brosnan", "funny|family|feelgood", "A divorced dad disguises himself as a nanny to see his kids."],
  // ── World cinema ─────────────────────────────────────────────────────────
  ["Parasite", 2019, 8.5, 1000, "m", "Comedy|Drama|Thriller", "KR", "Bong Joon-ho", "Song Kang-ho|Lee Sun-kyun|Cho Yeo-jeong", "twisty|dark|tense|funny", "A poor family schemes its way into a wealthy household."],
  ["Oldboy", 2003, 8.3, 650, "m", "Action|Drama|Mystery", "KR", "Park Chan-wook", "Choi Min-sik|Yoo Ji-tae|Kang Hye-jung", "dark|twisty|revenge", "A man imprisoned for 15 years without reason is suddenly released."],
  ["Memories of Murder", 2003, 8.1, 230, "m", "Crime|Drama|Mystery", "KR", "Bong Joon-ho", "Song Kang-ho|Kim Sang-kyung", "dark|tense|slowburn", "Two rural detectives chase Korea's first serial killer."],
  ["The Handmaiden", 2016, 8.1, 180, "m", "Drama|Romance|Thriller", "KR", "Park Chan-wook", "Kim Min-hee|Kim Tae-ri|Ha Jung-woo", "twisty|romantic|tense", "A con man and a maid plot to swindle a Japanese heiress."],
  ["Train to Busan", 2016, 7.6, 250, "m", "Action|Horror|Thriller", "KR", "Yeon Sang-ho", "Gong Yoo|Ma Dong-seok|Jung Yu-mi", "scary|tense|tearjerker|actionpacked", "Passengers fight to survive a zombie outbreak on a speeding train."],
  ["I Saw the Devil", 2010, 7.8, 140, "m", "Action|Crime|Horror", "KR", "Kim Jee-woon", "Lee Byung-hun|Choi Min-sik", "dark|revenge|tense", "A secret agent takes brutal revenge on his fiancée's killer."],
  ["Decision to Leave", 2022, 7.3, 50, "m", "Crime|Mystery|Romance", "KR", "Park Chan-wook", "Tang Wei|Park Hae-il", "slowburn|romantic|twisty", "A detective falls for the widow he suspects of murder."],
  ["Burning", 2018, 7.5, 75, "m", "Drama|Mystery", "KR", "Lee Chang-dong", "Yoo Ah-in|Steven Yeun|Jeon Jong-seo", "slowburn|mindbending|dark", "A young writer suspects his old friend's new boyfriend of something dark."],
  ["A Taxi Driver", 2017, 7.9, 25, "m", "Action|Drama|History", "KR", "Jang Hoon", "Song Kang-ho|Thomas Kretschmann", "inspiring|tearjerker", "A Seoul cab driver unwittingly drives a reporter into the Gwangju uprising."],
  ["20th Century Girl", 2022, 7.3, 15, "m", "Drama|Romance", "KR", "Bang Woo-ri", "Kim Yoo-jung|Byeon Woo-seok", "comingofage|bittersweet|romantic|nostalgic", "In 1999, a girl spies on a boy for her best friend and falls for his friend."],
  ["Miracle in Cell No. 7", 2013, 8.1, 20, "m", "Comedy|Drama", "KR", "Lee Hwan-kyung", "Ryu Seung-ryong|Kal So-won|Park Shin-hye", "tearjerker|family|funny", "Inmates help a wrongly convicted father reunite with his daughter."],
  ["The Classic", 2003, 7.9, 12, "m", "Drama|Romance", "KR", "Kwak Jae-yong", "Son Ye-jin|Jo In-sung|Cho Seung-woo", "romantic|tearjerker|nostalgic", "A daughter discovers her mother's first-love letters."],
  ["My Sassy Girl", 2001, 8.0, 50, "m", "Comedy|Drama|Romance", "KR", "Kwak Jae-yong", "Jun Ji-hyun|Cha Tae-hyun", "romantic|funny", "A gentle student is swept up by a wild, unpredictable girl."],
  ["The Wailing", 2016, 7.4, 65, "m", "Horror|Mystery", "KR", "Na Hong-jin", "Kwak Do-won|Hwang Jung-min|Jun Kunimura", "scary|dark|slowburn", "A village policeman investigates mysterious deaths after a stranger arrives."],
  ["Spirited Away", 2001, 8.6, 900, "m", "Animation|Adventure|Family|Fantasy", "JP", "Hayao Miyazaki", "Rumi Hiiragi|Miyu Irino", "cozy|family|feelgood|epic", "A girl must work in a spirit bathhouse to save her parents."],
  ["My Neighbor Totoro", 1988, 8.1, 400, "m", "Animation|Family|Fantasy", "JP", "Hayao Miyazaki", "Noriko Hidaka|Chika Sakamoto", "cozy|family|feelgood", "Two sisters befriend forest spirits in the Japanese countryside."],
  ["Howl's Moving Castle", 2004, 8.2, 450, "m", "Animation|Adventure|Family|Fantasy", "JP", "Hayao Miyazaki", "Chieko Baisho|Takuya Kimura", "cozy|romantic|feelgood", "A cursed young woman finds refuge in a wizard's walking castle."],
  ["Princess Mononoke", 1997, 8.3, 450, "m", "Animation|Adventure|Fantasy", "JP", "Hayao Miyazaki", "Yōji Matsuda|Yuriko Ishida", "epic|actionpacked", "A cursed prince is caught between a forest and the town destroying it."],
  ["Kiki's Delivery Service", 1989, 7.8, 170, "m", "Animation|Adventure|Family", "JP", "Hayao Miyazaki", "Minami Takayama|Rei Sakuma", "cozy|feelgood|comingofage", "A young witch starts a flying delivery service in a seaside town."],
  ["The Boy and the Heron", 2023, 7.4, 90, "m", "Animation|Adventure|Fantasy", "JP", "Hayao Miyazaki", "Soma Santoki|Masaki Suda", "thoughtful|mindbending", "A grieving boy follows a talking heron into another world."],
  ["Grave of the Fireflies", 1988, 8.5, 320, "m", "Animation|Drama|War", "JP", "Isao Takahata", "Tsutomu Tatsumi|Ayano Shiraishi", "tearjerker", "Two siblings struggle to survive in wartime Japan."],
  ["Your Name.", 2016, 8.4, 330, "m", "Animation|Drama|Fantasy|Romance", "JP", "Makoto Shinkai", "Ryunosuke Kamiki|Mone Kamishiraishi", "romantic|tearjerker|mindbending", "Two strangers mysteriously swap bodies, then search for each other."],
  ["Suzume", 2022, 7.6, 50, "m", "Animation|Adventure|Fantasy", "JP", "Makoto Shinkai", "Nanoka Hara|Hokuto Matsumura", "epic|romantic|tearjerker", "A girl travels Japan closing doors that unleash disaster."],
  ["A Silent Voice", 2016, 8.1, 120, "m", "Animation|Drama|Romance", "JP", "Naoko Yamada", "Miyu Irino|Saori Hayami", "tearjerker|comingofage", "A former bully seeks redemption with the deaf girl he tormented."],
  ["Perfect Blue", 1997, 8.0, 100, "m", "Animation|Horror|Mystery", "JP", "Satoshi Kon", "Junko Iwao|Rica Matsumoto", "mindbending|dark|scary", "A pop idol turned actress loses her grip on reality."],
  ["Akira", 1988, 8.0, 210, "m", "Animation|Action|Sci-Fi", "JP", "Katsuhiro Otomo", "Mitsuo Iwata|Nozomu Sasaki", "actionpacked|dark|epic", "A biker gang member gains devastating psychic powers in Neo-Tokyo."],
  ["Seven Samurai", 1954, 8.6, 370, "m", "Action|Drama", "JP", "Akira Kurosawa", "Toshiro Mifune|Takashi Shimura", "epic", "A village hires seven samurai to defend it from bandits."],
  ["Shoplifters", 2018, 7.9, 90, "m", "Crime|Drama", "JP", "Hirokazu Kore-eda", "Lily Franky|Sakura Ando", "tearjerker|thoughtful", "A family of small-time thieves takes in a neglected girl."],
  ["Drive My Car", 2021, 7.6, 60, "m", "Drama", "JP", "Ryusuke Hamaguchi", "Hidetoshi Nishijima|Tōko Miura", "slowburn|thoughtful", "A grieving actor-director bonds with his quiet young driver."],
  ["Godzilla Minus One", 2023, 7.7, 110, "m", "Action|Drama|Sci-Fi", "JP", "Takashi Yamazaki", "Ryunosuke Kamiki|Minami Hamabe", "epic|tearjerker|tense", "A war survivor faces Godzilla in devastated postwar Japan."],
  ["Crouching Tiger, Hidden Dragon", 2000, 7.9, 280, "m", "Action|Adventure|Fantasy", "TW", "Ang Lee", "Chow Yun-fat|Michelle Yeoh|Zhang Ziyi", "epic|romantic|actionpacked", "Warriors pursue a stolen legendary sword in Qing-dynasty China."],
  ["In the Mood for Love", 2000, 8.1, 170, "m", "Drama|Romance", "HK", "Wong Kar-wai", "Tony Leung Chiu-wai|Maggie Cheung", "romantic|slowburn|bittersweet", "Two neighbours suspect their spouses of an affair, and grow close."],
  ["Hero", 2002, 7.9, 190, "m", "Action|Adventure|History", "CN", "Zhang Yimou", "Jet Li|Tony Leung Chiu-wai|Maggie Cheung", "epic|actionpacked", "A nameless warrior recounts how he defeated three assassins."],
  ["Infernal Affairs", 2002, 8.0, 140, "m", "Crime|Mystery|Thriller", "HK", "Andrew Lau", "Andy Lau|Tony Leung Chiu-wai", "tense|twisty", "A police mole and a gang mole hunt for each other."],
  ["Farewell My Concubine", 1993, 8.1, 30, "m", "Drama|Music|Romance", "CN", "Chen Kaige", "Leslie Cheung|Zhang Fengyi|Gong Li", "tearjerker|epic", "Two Peking opera stars' bond survives fifty years of upheaval."],
  ["Kung Fu Hustle", 2004, 7.7, 160, "m", "Action|Comedy|Fantasy", "HK", "Stephen Chow", "Stephen Chow|Yuen Wah|Yuen Qiu", "funny|actionpacked", "A wannabe gangster stumbles into a slum full of kung fu masters."],
  ["Better Days", 2019, 8.2, 30, "m", "Crime|Drama|Romance", "CN", "Derek Tsang", "Zhou Dongyu|Jackson Yee", "tense|comingofage|tearjerker", "A bullied student and a street kid protect each other before the big exam."],
  ["You Are the Apple of My Eye", 2011, 7.6, 25, "m", "Comedy|Drama|Romance", "TW", "Giddens Ko", "Ko Chen-tung|Michelle Chen", "comingofage|bittersweet|romantic|nostalgic", "A class clown chases the top student through high school and beyond."],
  ["Our Times", 2015, 7.6, 10, "m", "Comedy|Drama|Romance", "TW", "Frankie Chen", "Vivian Sung|Darren Wang", "comingofage|nostalgic|romantic|funny", "An ordinary girl and the school bad boy team up to win their crushes."],
  ["Amélie", 2001, 8.3, 800, "m", "Comedy|Romance", "FR", "Jean-Pierre Jeunet", "Audrey Tautou|Mathieu Kassovitz", "cozy|feelgood|romantic", "A shy Parisian waitress secretly brightens the lives around her."],
  ["The Intouchables", 2011, 8.5, 950, "m", "Biography|Comedy|Drama", "FR", "Olivier Nakache", "Omar Sy|François Cluzet", "feelgood|inspiring|funny", "A rich quadriplegic hires a carer from the projects."],
  ["Portrait of a Lady on Fire", 2019, 8.1, 120, "m", "Drama|Romance", "FR", "Céline Sciamma", "Noémie Merlant|Adèle Haenel", "romantic|slowburn|bittersweet", "A painter is commissioned to secretly paint a reluctant bride."],
  ["Anatomy of a Fall", 2023, 7.7, 140, "m", "Crime|Drama|Thriller", "FR", "Justine Triet", "Sandra Hüller|Swann Arlaud", "tense|thoughtful|slowburn", "A writer is tried for her husband's death; their son is the key witness."],
  ["Life Is Beautiful", 1997, 8.6, 750, "m", "Comedy|Drama|Romance", "IT", "Roberto Benigni", "Roberto Benigni|Nicoletta Braschi", "tearjerker|feelgood|funny", "A father shields his son from the horrors of a camp with imagination."],
  ["Cinema Paradiso", 1988, 8.5, 280, "m", "Drama|Romance", "IT", "Giuseppe Tornatore", "Philippe Noiret|Salvatore Cascio", "nostalgic|tearjerker|cozy", "A filmmaker remembers the projectionist who shaped his childhood."],
  ["Pan's Labyrinth", 2006, 8.2, 700, "m", "Drama|Fantasy|War", "MX", "Guillermo del Toro", "Ivana Baquero|Sergi López|Maribel Verdú", "dark|tearjerker", "A girl escapes into a mythical labyrinth in Franco's Spain."],
  ["City of God", 2002, 8.6, 800, "m", "Crime|Drama", "BR", "Fernando Meirelles", "Alexandre Rodrigues|Leandro Firmino", "dark|tense", "Two boys grow up on opposite paths in Rio's favelas."],
  ["The Lives of Others", 2006, 8.4, 410, "m", "Drama|Thriller", "DE", "Florian Henckel von Donnersmarck", "Ulrich Mühe|Sebastian Koch|Martina Gedeck", "tense|thoughtful|tearjerker", "A Stasi agent spying on a writer begins to question his loyalty."],
  ["A Separation", 2011, 8.3, 260, "m", "Drama", "IR", "Asghar Farhadi", "Peyman Moaadi|Leila Hatami", "thoughtful|tense", "A couple's separation spirals into a moral crisis in Tehran."],
  ["The Hunt", 2012, 8.3, 360, "m", "Drama", "DK", "Thomas Vinterberg", "Mads Mikkelsen|Thomas Bo Larsen", "tense|dark", "A teacher's life collapses after a false accusation."],
  ["Another Round", 2020, 7.7, 200, "m", "Comedy|Drama", "DK", "Thomas Vinterberg", "Mads Mikkelsen|Thomas Bo Larsen", "bittersweet|funny", "Four teachers test a theory about staying slightly drunk."],
  ["The Invisible Guest", 2016, 8.0, 200, "m", "Crime|Drama|Mystery", "ES", "Oriol Paulo", "Mario Casas|Ana Wagener", "twisty|tense", "A businessman accused of murder has one night to build his defence."],
  ["The Platform", 2019, 7.0, 280, "m", "Horror|Sci-Fi|Thriller", "ES", "Galder Gaztelu-Urrutia", "Iván Massagué|Zorion Eguileor", "dark|tense|thoughtful", "Prisoners in a vertical jail share one descending table of food."],
  // ── India ────────────────────────────────────────────────────────────────
  ["3 Idiots", 2009, 8.4, 450, "m", "Comedy|Drama", "IN", "Rajkumar Hirani", "Aamir Khan|R. Madhavan|Sharman Joshi|Kareena Kapoor", "feelgood|funny|inspiring|tearjerker", "Two friends search for the college buddy who taught them to chase excellence."],
  ["Taare Zameen Par", 2007, 8.3, 210, "m", "Drama|Family", "IN", "Aamir Khan", "Darsheel Safary|Aamir Khan|Tisca Chopra", "tearjerker|inspiring|family", "An art teacher sees the gift in a boy everyone else has written off."],
  ["Dangal", 2016, 8.3, 210, "m", "Action|Biography|Drama|Sport", "IN", "Nitesh Tiwari", "Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra", "inspiring|feelgood", "A former wrestler trains his daughters to become champions."],
  ["PK", 2014, 8.1, 200, "m", "Comedy|Drama|Sci-Fi", "IN", "Rajkumar Hirani", "Aamir Khan|Anushka Sharma|Sushant Singh Rajput", "funny|thoughtful|feelgood", "An alien stranded in India asks innocent questions about faith."],
  ["Lagaan", 2001, 8.1, 120, "m", "Drama|Music|Sport", "IN", "Ashutosh Gowariker", "Aamir Khan|Gracy Singh|Rachel Shelley", "inspiring|epic", "Villagers bet their taxes on a cricket match against British officers."],
  ["Munna Bhai M.B.B.S.", 2003, 8.1, 90, "m", "Comedy|Drama", "IN", "Rajkumar Hirani", "Sanjay Dutt|Arshad Warsi|Gracy Singh", "funny|feelgood", "A big-hearted gangster enrols in medical school to please his father."],
  ["12th Fail", 2023, 8.7, 140, "m", "Biography|Drama", "IN", "Vidhu Vinod Chopra", "Vikrant Massey|Medha Shankr", "inspiring|tearjerker", "A boy from a Chambal village fights his way to the civil services."],
  ["Dilwale Dulhania Le Jayenge", 1995, 8.0, 75, "m", "Drama|Romance", "IN", "Aditya Chopra", "Shah Rukh Khan|Kajol|Amrish Puri", "romantic|feelgood|nostalgic|family", "Two young NRIs fall in love on a Europe trip; then comes her father."],
  ["Kuch Kuch Hota Hai", 1998, 7.5, 60, "m", "Comedy|Drama|Romance", "IN", "Karan Johar", "Shah Rukh Khan|Kajol|Rani Mukerji", "romantic|tearjerker|nostalgic", "A little girl plays matchmaker between her father and his college best friend."],
  ["Kabhi Khushi Kabhie Gham...", 2001, 7.4, 55, "m", "Drama|Music|Romance", "IN", "Karan Johar", "Amitabh Bachchan|Shah Rukh Khan|Kajol|Hrithik Roshan", "family|tearjerker|romantic", "A younger brother sets out to reunite his estranged family."],
  ["Kal Ho Naa Ho", 2003, 7.9, 80, "m", "Comedy|Drama|Romance", "IN", "Nikkhil Advani", "Shah Rukh Khan|Saif Ali Khan|Preity Zinta", "tearjerker|romantic|feelgood", "A cheerful stranger brings joy to a troubled New York family."],
  ["My Name Is Khan", 2010, 7.9, 110, "m", "Drama", "IN", "Karan Johar", "Shah Rukh Khan|Kajol", "inspiring|tearjerker", "A man with Asperger's sets out to meet the US President."],
  ["Chak De! India", 2007, 8.1, 90, "m", "Drama|Family|Sport", "IN", "Shimit Amin", "Shah Rukh Khan|Vidya Malvade|Sagarika Ghatge", "inspiring|feelgood", "A disgraced coach turns a fractured women's hockey team into champions."],
  ["Swades", 2004, 8.2, 95, "m", "Drama", "IN", "Ashutosh Gowariker", "Shah Rukh Khan|Gayatri Joshi", "inspiring|thoughtful|cozy", "A NASA scientist returns to India and finds his purpose in a village."],
  ["Devdas", 2002, 7.5, 50, "m", "Drama|Music|Romance", "IN", "Sanjay Leela Bhansali", "Shah Rukh Khan|Aishwarya Rai|Madhuri Dixit", "tearjerker|romantic|epic", "A heartbroken heir drowns his lost love in drink."],
  ["Om Shanti Om", 2007, 6.7, 60, "m", "Action|Comedy|Drama", "IN", "Farah Khan", "Shah Rukh Khan|Deepika Padukone|Arjun Rampal", "funny|romantic|revenge", "A junior artist reborn decades later seeks justice for a lost star."],
  ["Jawan", 2023, 6.9, 110, "m", "Action|Thriller", "IN", "Atlee", "Shah Rukh Khan|Nayanthara|Vijay Sethupathi", "actionpacked|revenge", "A man leads a team of women to right the wrongs of society."],
  ["Pathaan", 2023, 5.8, 130, "m", "Action|Thriller", "IN", "Siddharth Anand", "Shah Rukh Khan|Deepika Padukone|John Abraham", "actionpacked", "An exiled spy returns to stop a rogue agent's attack on India."],
  ["Zindagi Na Milegi Dobara", 2011, 8.2, 90, "m", "Comedy|Drama", "IN", "Zoya Akhtar", "Hrithik Roshan|Farhan Akhtar|Abhay Deol|Katrina Kaif", "feelgood|funny|inspiring", "Three friends on a Spanish road trip confront their fears."],
  ["Yeh Jawaani Hai Deewani", 2013, 7.2, 75, "m", "Comedy|Drama|Romance", "IN", "Ayan Mukerji", "Ranbir Kapoor|Deepika Padukone|Aditya Roy Kapur", "romantic|feelgood|comingofage", "A wanderer and a bookworm reconnect years after a trek."],
  ["Barfi!", 2012, 8.1, 90, "m", "Comedy|Drama|Romance", "IN", "Anurag Basu", "Ranbir Kapoor|Priyanka Chopra|Ileana D'Cruz", "feelgood|tearjerker|romantic", "A charming deaf-mute man and the two women who love him."],
  ["Rockstar", 2011, 7.7, 45, "m", "Drama|Music|Romance", "IN", "Imtiaz Ali", "Ranbir Kapoor|Nargis Fakhri", "bittersweet|romantic", "A college boy's heartbreak turns him into a tortured rock star."],
  ["Jab We Met", 2007, 7.9, 55, "m", "Comedy|Drama|Romance", "IN", "Imtiaz Ali", "Shahid Kapoor|Kareena Kapoor", "romantic|feelgood|funny", "A heartbroken tycoon meets a chatterbox on an overnight train."],
  ["Queen", 2013, 8.1, 70, "m", "Adventure|Comedy|Drama", "IN", "Vikas Bahl", "Kangana Ranaut|Rajkummar Rao|Lisa Haydon", "feelgood|inspiring|funny", "Dumped before her wedding, a girl goes on her honeymoon alone."],
  ["Andhadhun", 2018, 8.2, 110, "m", "Crime|Mystery|Thriller", "IN", "Sriram Raghavan", "Ayushmann Khurrana|Tabu|Radhika Apte", "twisty|funny|tense", "A 'blind' pianist accidentally witnesses a murder."],
  ["Drishyam", 2015, 8.2, 95, "m", "Crime|Drama|Mystery", "IN", "Nishikant Kamat", "Ajay Devgn|Tabu|Shriya Saran", "twisty|tense", "A film-loving father hides his family's secret from a relentless IG."],
  ["Kahaani", 2012, 8.1, 70, "m", "Mystery|Thriller", "IN", "Sujoy Ghosh", "Vidya Balan|Parambrata Chatterjee|Nawazuddin Siddiqui", "twisty|tense", "A pregnant woman searches Kolkata for her missing husband."],
  ["Gangs of Wasseypur", 2012, 8.2, 105, "m", "Action|Comedy|Crime", "IN", "Anurag Kashyap", "Manoj Bajpayee|Nawazuddin Siddiqui|Richa Chadha", "dark|revenge|funny", "A coal-town blood feud spans three generations."],
  ["Sholay", 1975, 8.1, 60, "m", "Action|Adventure|Comedy", "IN", "Ramesh Sippy", "Amitabh Bachchan|Dharmendra|Hema Malini|Amjad Khan", "epic|nostalgic|revenge", "Two small-time crooks are hired to capture a ruthless dacoit."],
  ["Anand", 1971, 8.7, 35, "m", "Drama|Music", "IN", "Hrishikesh Mukherjee", "Rajesh Khanna|Amitabh Bachchan", "tearjerker|feelgood|nostalgic", "A terminally ill man fills every moment with life."],
  ["Hera Pheri", 2000, 8.1, 75, "m", "Action|Comedy|Crime", "IN", "Priyadarshan", "Akshay Kumar|Suniel Shetty|Paresh Rawal", "funny", "Three broke men get tangled in a kidnapping call meant for someone else."],
  ["Bajrangi Bhaijaan", 2015, 8.1, 100, "m", "Action|Comedy|Drama", "IN", "Kabir Khan", "Salman Khan|Harshaali Malhotra|Kareena Kapoor", "tearjerker|feelgood|family", "A devout man takes a lost mute girl home across the border."],
  ["Gully Boy", 2019, 7.9, 70, "m", "Drama|Music", "IN", "Zoya Akhtar", "Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi", "inspiring|feelgood", "A street rapper from Mumbai's slums finds his voice."],
  ["Rocky Aur Rani Kii Prem Kahaani", 2023, 6.6, 40, "m", "Comedy|Drama|Romance", "IN", "Karan Johar", "Ranveer Singh|Alia Bhatt|Dharmendra", "romantic|funny|family", "Opposites in love swap families to win each other's parents over."],
  ["Animal", 2023, 6.1, 120, "m", "Action|Crime|Drama", "IN", "Sandeep Reddy Vanga", "Ranbir Kapoor|Anil Kapoor|Rashmika Mandanna", "actionpacked|dark|revenge", "A son's obsessive love for his father turns violent."],
  ["Piku", 2015, 7.6, 40, "m", "Comedy|Drama", "IN", "Shoojit Sircar", "Deepika Padukone|Amitabh Bachchan|Irrfan Khan", "cozy|feelgood|funny", "A daughter road-trips to Kolkata with her cranky father."],
  ["The Lunchbox", 2013, 7.8, 60, "m", "Drama|Romance", "IN", "Ritesh Batra", "Irrfan Khan|Nimrat Kaur|Nawazuddin Siddiqui", "cozy|bittersweet|romantic", "A mistaken lunch delivery sparks letters between two lonely strangers."],
  ["Stree", 2018, 7.5, 45, "m", "Comedy|Horror", "IN", "Amar Kaushik", "Rajkummar Rao|Shraddha Kapoor|Pankaj Tripathi", "funny|scary", "A small town is haunted by a spirit who abducts men at night."],
  ["Tumbbad", 2018, 8.2, 60, "m", "Drama|Fantasy|Horror", "IN", "Rahi Anil Barve", "Sohum Shah|Jyoti Malshe", "scary|dark", "A man's greed for a cursed treasure spans generations."],
  ["Uri: The Surgical Strike", 2019, 8.2, 70, "m", "Action|Drama|War", "IN", "Aditya Dhar", "Vicky Kaushal|Yami Gautam|Paresh Rawal", "actionpacked|tense", "An army officer leads a covert retaliatory strike."],
  ["Laapataa Ladies", 2023, 8.4, 40, "m", "Comedy|Drama", "IN", "Kiran Rao", "Nitanshi Goel|Pratibha Ranta|Sparsh Shrivastava", "feelgood|funny|cozy", "Two veiled brides are swapped on a train."],
  ["RRR", 2022, 7.8, 170, "m", "Action|Drama", "IN", "S.S. Rajamouli", "N.T. Rama Rao Jr.|Ram Charan|Alia Bhatt", "epic|actionpacked", "Two revolutionaries forge a friendship against the British Raj."],
  ["Baahubali: The Beginning", 2015, 8.0, 140, "m", "Action|Drama|Fantasy", "IN", "S.S. Rajamouli", "Prabhas|Rana Daggubati|Anushka Shetty", "epic|actionpacked", "A young man discovers his royal lineage and a kingdom's dark past."],
  ["Baahubali 2: The Conclusion", 2017, 8.2, 120, "m", "Action|Drama|Fantasy", "IN", "S.S. Rajamouli", "Prabhas|Rana Daggubati|Anushka Shetty", "epic|actionpacked|revenge", "Why did Kattappa kill Baahubali? The saga concludes."],
  ["K.G.F: Chapter 2", 2022, 8.2, 150, "m", "Action|Crime|Drama", "IN", "Prashanth Neel", "Yash|Sanjay Dutt|Srinidhi Shetty", "actionpacked|epic", "Rocky's bloody reign over the gold fields faces its biggest threats."],
  ["Kantara", 2022, 8.2, 110, "m", "Action|Adventure|Drama", "IN", "Rishab Shetty", "Rishab Shetty|Sapthami Gowda|Kishore", "epic|dark", "A coastal village's rituals collide with a land dispute."],
  ["Vikram", 2022, 8.3, 70, "m", "Action|Crime|Thriller", "IN", "Lokesh Kanagaraj", "Kamal Haasan|Vijay Sethupathi|Fahadh Faasil", "actionpacked|twisty", "A black-ops squad hunts masked men targeting a drug syndicate."],
  ["Jai Bhim", 2021, 8.7, 210, "m", "Crime|Drama", "IN", "Tha. Se. Gnanavel", "Suriya|Lijomol Jose|Manikandan", "inspiring|tearjerker", "A lawyer fights for a tribal woman whose husband vanished in custody."],
  ["Soorarai Pottru", 2020, 8.7, 120, "m", "Drama", "IN", "Sudha Kongara", "Suriya|Aparna Balamurali|Paresh Rawal", "inspiring|romantic", "A village man dreams of launching a low-cost airline."],
  ["Sita Ramam", 2022, 8.5, 70, "m", "Drama|Romance|War", "IN", "Hanu Raghavapudi", "Dulquer Salmaan|Mrunal Thakur|Rashmika Mandanna", "romantic|tearjerker|nostalgic", "An orphaned soldier receives letters from a mysterious woman."],
  ["Premam", 2015, 8.3, 25, "m", "Comedy|Drama|Romance", "IN", "Alphonse Puthren", "Nivin Pauly|Sai Pallavi|Madonna Sebastian", "romantic|feelgood|comingofage", "One man's three loves, from schoolboy to adulthood."],
  ["Kumbalangi Nights", 2019, 8.5, 30, "m", "Comedy|Drama|Romance", "IN", "Madhu C. Narayanan", "Fahadh Faasil|Soubin Shahir|Shane Nigam", "cozy|feelgood|funny", "Four estranged brothers in a fishing village learn to be family."],
  ["Manjummel Boys", 2024, 8.2, 30, "m", "Adventure|Drama|Thriller", "IN", "Chidambaram", "Soubin Shahir|Sreenath Bhasi", "tense|inspiring", "Friends on a trip mount a rescue when one falls into a deep cave."],
  ["Pather Panchali", 1955, 8.2, 35, "m", "Drama", "IN", "Satyajit Ray", "Kanu Bannerjee|Karuna Bannerjee|Subir Banerjee", "slowburn|tearjerker", "A poor Bengali family's life through the eyes of young Apu."],
  // ── TV series ────────────────────────────────────────────────────────────
  ["Breaking Bad", 2008, 9.5, 2200, "s", "Crime|Drama|Thriller", "US", "Vince Gilligan", "Bryan Cranston|Aaron Paul|Anna Gunn", "dark|tense", "A chemistry teacher turns meth kingpin."],
  ["Better Call Saul", 2015, 9.0, 700, "s", "Crime|Drama", "US", "Vince Gilligan", "Bob Odenkirk|Rhea Seehorn|Jonathan Banks", "slowburn|funny|dark", "A small-time lawyer slowly becomes Saul Goodman."],
  ["Game of Thrones", 2011, 9.2, 2300, "s", "Action|Adventure|Drama|Fantasy", "US", "David Benioff", "Emilia Clarke|Peter Dinklage|Kit Harington", "epic|dark|twisty", "Noble families fight for the Iron Throne as winter comes."],
  ["House of the Dragon", 2022, 8.3, 500, "s", "Action|Adventure|Drama|Fantasy", "US", "Ryan Condal", "Paddy Considine|Emma D'Arcy|Matt Smith", "epic|dark", "House Targaryen tears itself apart in a war of succession."],
  ["Chernobyl", 2019, 9.3, 950, "s", "Drama|History|Thriller", "UK", "Craig Mazin", "Jared Harris|Stellan Skarsgård|Emily Watson", "tense|dark|thoughtful", "The 1986 nuclear disaster and the people who contained it."],
  ["The Last of Us", 2023, 8.6, 600, "s", "Action|Adventure|Drama", "US", "Craig Mazin", "Pedro Pascal|Bella Ramsey", "epic|tearjerker|tense", "A smuggler escorts a teenage girl across a ruined America."],
  ["Band of Brothers", 2001, 9.4, 550, "s", "Drama|History|War", "US", "Steven Spielberg", "Damian Lewis|Ron Livingston|Scott Grimes", "epic|tense|tearjerker", "Easy Company's journey from D-Day to the end of the war."],
  ["The Sopranos", 1999, 9.2, 500, "s", "Crime|Drama", "US", "David Chase", "James Gandolfini|Lorraine Bracco|Edie Falco", "dark|funny", "A New Jersey mob boss sees a therapist."],
  ["The Wire", 2002, 9.3, 400, "s", "Crime|Drama|Thriller", "US", "David Simon", "Dominic West|Idris Elba|Lance Reddick", "slowburn|thoughtful", "Baltimore's drug war seen from the streets to city hall."],
  ["Sherlock", 2010, 9.1, 1000, "s", "Crime|Drama|Mystery", "UK", "Steven Moffat", "Benedict Cumberbatch|Martin Freeman", "twisty|funny", "A modern Sherlock Holmes solves crimes in London."],
  ["True Detective", 2014, 8.9, 650, "s", "Crime|Drama|Mystery", "US", "Nic Pizzolatto", "Matthew McConaughey|Woody Harrelson", "dark|slowburn|tense", "Two detectives revisit a ritualistic murder case across 17 years."],
  ["Mindhunter", 2017, 8.6, 330, "s", "Crime|Drama|Thriller", "US", "Joe Penhall", "Jonathan Groff|Holt McCallany|Anna Torv", "dark|tense|slowburn", "FBI agents interview serial killers to understand them."],
  ["Stranger Things", 2016, 8.7, 1400, "s", "Drama|Fantasy|Horror", "US", "The Duffer Brothers", "Millie Bobby Brown|Winona Ryder|David Harbour", "nostalgic|scary|comingofage|actionpacked", "Kids in 1980s Indiana face a secret lab and a monster world."],
  ["Wednesday", 2022, 8.0, 450, "s", "Comedy|Crime|Fantasy", "US", "Alfred Gough", "Jenna Ortega|Gwendoline Christie|Emma Myers", "funny|twisty|comingofage", "Wednesday Addams investigates murders at her new school."],
  ["Friends", 1994, 8.9, 1100, "s", "Comedy|Romance", "US", "David Crane", "Jennifer Aniston|Courteney Cox|Matthew Perry", "funny|cozy|feelgood|nostalgic", "Six friends navigate life and love in Manhattan."],
  ["The Office", 2005, 9.0, 750, "s", "Comedy", "US", "Greg Daniels", "Steve Carell|Rainn Wilson|John Krasinski", "funny|cozy", "A mockumentary about the weird lives of paper-company workers."],
  ["Parks and Recreation", 2009, 8.6, 300, "s", "Comedy", "US", "Greg Daniels", "Amy Poehler|Nick Offerman|Aubrey Plaza", "funny|cozy|feelgood", "An optimistic bureaucrat tries to make her small town better."],
  ["Brooklyn Nine-Nine", 2013, 8.4, 380, "s", "Comedy|Crime", "US", "Dan Goor", "Andy Samberg|Andre Braugher|Stephanie Beatriz", "funny|feelgood|cozy", "A goofy detective and his precinct under a stoic captain."],
  ["How I Met Your Mother", 2005, 8.3, 750, "s", "Comedy|Romance", "US", "Carter Bays", "Josh Radnor|Neil Patrick Harris|Cobie Smulders", "funny|romantic|cozy", "A father tells his kids the long story of meeting their mother."],
  ["The Big Bang Theory", 2007, 8.1, 900, "s", "Comedy|Romance", "US", "Chuck Lorre", "Johnny Galecki|Jim Parsons|Kaley Cuoco", "funny|cozy", "Two physicists' lives change when a new neighbour moves in."],
  ["Modern Family", 2009, 8.5, 480, "s", "Comedy|Drama|Romance", "US", "Steven Levitan", "Ed O'Neill|Sofía Vergara|Julie Bowen", "funny|family|cozy", "Three branches of one big, chaotic family."],
  ["Ted Lasso", 2020, 8.8, 360, "s", "Comedy|Drama|Sport", "US", "Bill Lawrence", "Jason Sudeikis|Hannah Waddingham|Brett Goldstein", "feelgood|funny|inspiring|cozy", "An American football coach takes over an English soccer team."],
  ["Schitt's Creek", 2015, 8.5, 140, "s", "Comedy", "US", "Dan Levy", "Eugene Levy|Catherine O'Hara|Dan Levy", "funny|cozy|feelgood", "A rich family loses everything and moves to a tiny town."],
  ["Gilmore Girls", 2000, 8.2, 230, "s", "Comedy|Drama", "US", "Amy Sherman-Palladino", "Lauren Graham|Alexis Bledel", "cozy|feelgood|funny", "A fast-talking mother and daughter in a quirky Connecticut town."],
  ["Only Murders in the Building", 2021, 8.1, 170, "s", "Comedy|Crime|Mystery", "US", "Steve Martin", "Steve Martin|Martin Short|Selena Gomez", "cozy|funny|twisty", "Three true-crime fans investigate a death in their building."],
  ["Succession", 2018, 8.9, 300, "s", "Comedy|Drama", "US", "Jesse Armstrong", "Brian Cox|Jeremy Strong|Sarah Snook", "dark|funny|tense", "A media mogul's children scheme for control of his empire."],
  ["The Bear", 2022, 8.5, 230, "s", "Comedy|Drama", "US", "Christopher Storer", "Jeremy Allen White|Ayo Edebiri|Ebon Moss-Bachrach", "tense|thoughtful", "A fine-dining chef returns home to run his family's sandwich shop."],
  ["Severance", 2022, 8.7, 250, "s", "Drama|Mystery|Sci-Fi", "US", "Dan Erickson", "Adam Scott|Britt Lower|Patricia Arquette", "mindbending|twisty|tense", "Office workers have their work and home memories surgically split."],
  ["The Queen's Gambit", 2020, 8.5, 600, "s", "Drama|Sport", "US", "Scott Frank", "Anya Taylor-Joy|Bill Camp", "inspiring|comingofage", "An orphaned chess prodigy fights addiction on her way to the top."],
  ["Ozark", 2017, 8.5, 400, "s", "Crime|Drama|Thriller", "US", "Bill Dubuque", "Jason Bateman|Laura Linney|Julia Garner", "tense|dark", "A financial adviser launders money for a cartel in the Ozarks."],
  ["Narcos", 2015, 8.7, 450, "s", "Biography|Crime|Drama", "US", "Chris Brancato", "Wagner Moura|Pedro Pascal|Boyd Holbrook", "tense|dark", "The DEA's hunt for Pablo Escobar."],
  ["The Boys", 2019, 8.6, 750, "s", "Action|Comedy|Crime", "US", "Eric Kripke", "Karl Urban|Jack Quaid|Antony Starr", "dark|funny|actionpacked", "Vigilantes take on corrupt superheroes."],
  ["The Mandalorian", 2019, 8.6, 600, "s", "Action|Adventure|Fantasy", "US", "Jon Favreau", "Pedro Pascal|Gina Carano|Carl Weathers", "actionpacked|feelgood|epic", "A lone bounty hunter protects a mysterious child."],
  ["Arcane", 2021, 9.0, 350, "s", "Animation|Action|Adventure", "US", "Christian Linke", "Hailee Steinfeld|Ella Purnell|Kevin Alejandro", "epic|actionpacked|tearjerker", "Two sisters end up on opposite sides of a war between cities."],
  ["Avatar: The Last Airbender", 2005, 9.3, 380, "s", "Animation|Action|Adventure", "US", "Michael Dante DiMartino", "Zach Tyler Eisen|Mae Whitman|Dante Basco", "epic|family|funny|feelgood", "A young Avatar must master four elements to end a war."],
  ["Bridgerton", 2020, 7.3, 200, "s", "Drama|Romance", "US", "Chris Van Dusen", "Phoebe Dynevor|Regé-Jean Page|Jonathan Bailey", "romantic|cozy", "Romance and scandal in Regency London's marriage season."],
  ["Shōgun", 2024, 8.6, 250, "s", "Adventure|Drama|History", "US", "Rachel Kondo", "Hiroyuki Sanada|Cosmo Jarvis|Anna Sawai", "epic|tense|slowburn", "An English sailor is caught in a power struggle in feudal Japan."],
  ["The Crown", 2016, 8.6, 270, "s", "Biography|Drama|History", "UK", "Peter Morgan", "Claire Foy|Olivia Colman|Imelda Staunton", "thoughtful|slowburn", "The reign of Queen Elizabeth II, decade by decade."],
  ["Peaky Blinders", 2013, 8.8, 700, "s", "Crime|Drama", "UK", "Steven Knight", "Cillian Murphy|Paul Anderson|Helen McCrory", "dark|tense", "A Birmingham gang family's rise after World War I."],
  ["Black Mirror", 2011, 8.7, 650, "s", "Drama|Mystery|Sci-Fi", "UK", "Charlie Brooker", "", "mindbending|dark|thoughtful", "Standalone stories about technology's dark side."],
  ["Fleabag", 2016, 8.7, 120, "s", "Comedy|Drama", "UK", "Phoebe Waller-Bridge", "Phoebe Waller-Bridge|Sian Clifford|Andrew Scott", "funny|bittersweet", "A grieving, sharp-tongued woman navigates London life."],
  ["Normal People", 2020, 8.4, 120, "s", "Drama|Romance", "IE", "Sally Rooney", "Daisy Edgar-Jones|Paul Mescal", "romantic|bittersweet|slowburn|comingofage", "Two teens' on-and-off love from school through university."],
  ["Heartstopper", 2022, 8.6, 90, "s", "Comedy|Drama|Romance", "UK", "Alice Oseman", "Kit Connor|Joe Locke", "feelgood|romantic|comingofage|cozy", "Two British schoolboys become friends and fall in love."],
  ["Dark", 2017, 8.7, 480, "s", "Crime|Drama|Mystery|Sci-Fi", "DE", "Baran bo Odar", "Louis Hofmann|Lisa Vicari|Oliver Masucci", "mindbending|dark|twisty", "A missing child exposes a small town's time-travel secrets."],
  ["Money Heist", 2017, 8.2, 550, "s", "Action|Crime|Drama", "ES", "Álex Pina", "Úrsula Corberó|Álvaro Morte|Itziar Ituño", "tense|twisty|actionpacked", "A mastermind leads robbers in a heist on Spain's Royal Mint."],
  ["Lupin", 2021, 7.5, 140, "s", "Action|Crime|Drama", "FR", "George Kay", "Omar Sy|Ludivine Sagnier", "twisty|feelgood", "A gentleman thief sets out to avenge his father."],
  ["Panchayat", 2020, 9.0, 100, "s", "Comedy|Drama", "IN", "Deepak Kumar Mishra", "Jitendra Kumar|Raghubir Yadav|Neena Gupta", "cozy|feelgood|funny", "An engineering graduate becomes secretary of a remote village office."],
  ["Gullak", 2019, 9.1, 25, "s", "Comedy|Drama|Family", "IN", "Amrit Raj Gupta", "Jameel Khan|Geetanjali Kulkarni|Vaibhav Raj Gupta", "cozy|family|feelgood", "Small joys and squabbles of a middle-class family."],
  ["Kota Factory", 2019, 9.0, 85, "s", "Comedy|Drama", "IN", "Raghav Subbu", "Jitendra Kumar|Mayur More|Ranjan Raj", "comingofage|inspiring", "Students in Kota's coaching factories chase IIT dreams."],
  ["Scam 1992: The Harshad Mehta Story", 2020, 9.2, 160, "s", "Biography|Crime|Drama", "IN", "Hansal Mehta", "Pratik Gandhi|Shreya Dhanwanthary", "tense|inspiring", "A stockbroker's meteoric rise and the scam that brought him down."],
  ["The Family Man", 2019, 8.7, 100, "s", "Action|Comedy|Drama", "IN", "Raj & DK", "Manoj Bajpayee|Priyamani|Sharib Hashmi", "funny|tense|actionpacked", "A middle-class man secretly works as an intelligence officer."],
  ["Sacred Games", 2018, 8.5, 110, "s", "Action|Crime|Thriller", "IN", "Anurag Kashyap", "Saif Ali Khan|Nawazuddin Siddiqui|Radhika Apte", "dark|tense", "A cop gets a tip that Mumbai has 25 days to survive."],
  ["Mirzapur", 2018, 8.4, 90, "s", "Action|Crime|Thriller", "IN", "Karan Anshuman", "Pankaj Tripathi|Ali Fazal|Divyenndu", "dark|actionpacked|revenge", "A mafia don's lawless rule in a north Indian town."],
  ["Attack on Titan", 2013, 9.1, 550, "s", "Animation|Action|Adventure", "JP", "Hajime Isayama", "Yuki Kaji|Yui Ishikawa|Marina Inoue", "epic|dark|twisty", "Humanity fights man-eating giants from behind towering walls."],
  ["Death Note", 2006, 8.9, 450, "s", "Animation|Crime|Mystery", "JP", "Tetsuro Araki", "Mamoru Miyano|Kappei Yamaguchi", "twisty|dark|tense", "A student finds a notebook that kills anyone whose name is written in it."],
  ["Fullmetal Alchemist: Brotherhood", 2009, 9.1, 230, "s", "Animation|Action|Adventure", "JP", "Yasuhiro Irie", "Romi Park|Rie Kugimiya", "epic|tearjerker", "Two brothers seek the Philosopher's Stone after a failed alchemy."],
  ["One Piece", 1999, 9.0, 260, "s", "Animation|Action|Adventure", "JP", "Eiichiro Oda", "Mayumi Tanaka|Kazuya Nakai", "epic|funny|feelgood", "A rubber-limbed pirate sails to find the legendary One Piece."],
  ["Demon Slayer", 2019, 8.6, 200, "s", "Animation|Action|Fantasy", "JP", "Haruo Sotozaki", "Natsuki Hanae|Akari Kito", "actionpacked|tearjerker", "A boy becomes a demon slayer to save his sister."],
  ["Jujutsu Kaisen", 2020, 8.5, 140, "s", "Animation|Action|Fantasy", "JP", "Sunghoo Park", "Junya Enoki|Yuichi Nakamura", "actionpacked|dark", "A student swallows a cursed finger and joins a school of sorcerers."],
  ["Cowboy Bebop", 1998, 8.9, 140, "s", "Animation|Action|Sci-Fi", "JP", "Shinichirō Watanabe", "Kōichi Yamadera|Unshō Ishizuka", "slowburn|actionpacked|bittersweet", "Bounty hunters drift through space to a jazz soundtrack."],
  ["Your Lie in April", 2014, 8.5, 60, "s", "Animation|Drama|Music|Romance", "JP", "Kyohei Ishiguro", "Natsuki Hanae|Risa Taneda", "tearjerker|romantic|comingofage", "A pianist who lost his music meets a free-spirited violinist."],
  ["Spy x Family", 2022, 8.3, 60, "s", "Animation|Action|Comedy", "JP", "Kazuhiro Furuhashi", "Takuya Eguchi|Atsumi Tanezaki|Saori Hayami", "funny|cozy|family|feelgood", "A spy, an assassin and a telepath form a fake family."],
  ["Frieren: Beyond Journey's End", 2023, 8.9, 40, "s", "Animation|Adventure|Drama|Fantasy", "JP", "Keiichiro Saito", "Atsumi Tanezaki|Kana Ichinose", "cozy|bittersweet|thoughtful", "An elf mage learns what her human companions meant to her."],
  ["Violet Evergarden", 2018, 8.4, 40, "s", "Animation|Drama|Fantasy", "JP", "Taichi Ishidate", "Yui Ishikawa|Daisuke Namikawa", "tearjerker|slowburn", "A former child soldier writes letters to understand love."],
  ["Neon Genesis Evangelion", 1995, 8.5, 90, "s", "Animation|Action|Drama", "JP", "Hideaki Anno", "Megumi Ogata|Kotono Mitsuishi", "mindbending|dark", "Teen pilots in giant robots fight mysterious beings called Angels."],
  // ── K-dramas ─────────────────────────────────────────────────────────────
  ["Squid Game", 2021, 8.0, 600, "s", "Action|Drama|Thriller", "KR", "Hwang Dong-hyuk", "Lee Jung-jae|Park Hae-soo|Jung Ho-yeon", "tense|dark", "Debt-ridden players risk their lives in deadly children's games."],
  ["Crash Landing on You", 2019, 8.7, 45, "s", "Comedy|Drama|Romance", "KR", "Lee Jeong-hyo", "Hyun Bin|Son Ye-jin|Seo Ji-hye", "romantic|funny|tearjerker", "A South Korean heiress crash-lands in North Korea and into love."],
  ["Goblin", 2016, 8.6, 30, "s", "Comedy|Drama|Fantasy|Romance", "KR", "Lee Eung-bok", "Gong Yoo|Kim Go-eun|Lee Dong-wook", "romantic|bittersweet|epic|tearjerker", "An immortal goblin seeks the bride who can end his life."],
  ["Reply 1988", 2015, 9.2, 25, "s", "Comedy|Drama|Romance", "KR", "Shin Won-ho", "Lee Hye-ri|Park Bo-gum|Ryu Jun-yeol", "cozy|nostalgic|feelgood|tearjerker", "Five families in one Seoul alley share the year 1988."],
  ["Hospital Playlist", 2020, 8.9, 20, "s", "Comedy|Drama", "KR", "Shin Won-ho", "Jo Jung-suk|Yoo Yeon-seok|Jeon Mi-do", "cozy|feelgood|funny", "Five doctors and lifelong friends share work, life and music."],
  ["Prison Playbook", 2017, 8.7, 8, "s", "Comedy|Crime|Drama", "KR", "Shin Won-ho", "Park Hae-soo|Jung Kyung-ho", "funny|feelgood", "A star pitcher lands in prison and learns life on the inside."],
  ["My Mister", 2018, 9.1, 20, "s", "Drama", "KR", "Kim Won-seok", "Lee Sun-kyun|IU", "slowburn|tearjerker|thoughtful", "A weary engineer and a struggling young woman heal each other."],
  ["When Life Gives You Tangerines", 2025, 9.1, 10, "s", "Drama|Romance", "KR", "Kim Won-seok", "IU|Park Bo-gum", "tearjerker|romantic|family|nostalgic", "A lifelong love story on Jeju Island, season by season."],
  ["Signal", 2016, 8.5, 15, "s", "Crime|Fantasy|Mystery", "KR", "Kim Won-seok", "Lee Je-hoon|Kim Hye-soo|Cho Jin-woong", "tense|twisty|mindbending", "A walkie-talkie connects detectives across time to solve cold cases."],
  ["Mr. Sunshine", 2018, 8.8, 15, "s", "Drama|History|Romance", "KR", "Lee Eung-bok", "Lee Byung-hun|Kim Tae-ri|Yoo Yeon-seok", "epic|tearjerker|romantic", "A US marine returns to Joseon and falls for a noblewoman freedom fighter."],
  ["Descendants of the Sun", 2016, 8.2, 25, "s", "Action|Drama|Romance", "KR", "Lee Eung-bok", "Song Joong-ki|Song Hye-kyo", "romantic|actionpacked", "A special forces captain and a surgeon fall in love on missions abroad."],
  ["Itaewon Class", 2020, 8.2, 25, "s", "Drama|Romance", "KR", "Kim Sung-yoon", "Park Seo-joon|Kim Da-mi", "inspiring|revenge", "An ex-con opens a bar in Itaewon to take down the man who ruined him."],
  ["Extraordinary Attorney Woo", 2022, 8.5, 25, "s", "Comedy|Drama", "KR", "Yoo In-shik", "Park Eun-bin|Kang Tae-oh|Kang Ki-young", "feelgood|cozy|inspiring", "A brilliant autistic lawyer starts at a top Seoul firm."],
  ["Business Proposal", 2022, 8.1, 25, "s", "Comedy|Romance", "KR", "Park Seon-ho", "Ahn Hyo-seop|Kim Se-jeong", "romantic|funny|cozy", "A blind date in disguise lands her in front of her own CEO."],
  ["Hometown Cha-Cha-Cha", 2021, 8.6, 25, "s", "Comedy|Drama|Romance", "KR", "Yoo Je-won", "Shin Min-a|Kim Seon-ho", "cozy|romantic|feelgood", "A city dentist moves to a seaside village and its handyman."],
  ["Vincenzo", 2021, 8.4, 30, "s", "Comedy|Crime|Drama", "KR", "Kim Hee-won", "Song Joong-ki|Jeon Yeo-been|Ok Taec-yeon", "funny|revenge|actionpacked", "A Korean-Italian mafia lawyer fights a corrupt conglomerate."],
  ["The Glory", 2022, 8.1, 50, "s", "Drama|Thriller", "KR", "Ahn Gil-ho", "Song Hye-kyo|Lee Do-hyun|Lim Ji-yeon", "revenge|dark|tense", "A woman spends years planning revenge on her school bullies."],
  ["Stranger", 2017, 8.6, 10, "s", "Crime|Drama|Mystery", "KR", "Ahn Gil-ho", "Cho Seung-woo|Bae Doona", "tense|twisty|slowburn", "An emotionless prosecutor and a detective uncover corruption."],
  ["Twenty-Five Twenty-One", 2022, 8.6, 20, "s", "Drama|Romance", "KR", "Jung Ji-hyun", "Kim Tae-ri|Nam Joo-hyuk", "comingofage|bittersweet|romantic|nostalgic", "A teen fencer and a young reporter grow up together in 1998."],
  ["Lovely Runner", 2024, 8.6, 15, "s", "Comedy|Fantasy|Romance", "KR", "Yoon Jong-ho", "Byeon Woo-seok|Kim Hye-yoon", "romantic|feelgood|tearjerker", "A fan travels back in time to save her favourite star."],
  ["Queen of Tears", 2024, 8.2, 25, "s", "Comedy|Drama|Romance", "KR", "Jang Young-woo", "Kim Soo-hyun|Kim Ji-won", "romantic|tearjerker|funny", "A chaebol heiress and her husband rediscover love in crisis."],
  ["It's Okay to Not Be Okay", 2020, 8.6, 30, "s", "Comedy|Drama|Romance", "KR", "Park Shin-woo", "Kim Soo-hyun|Seo Yea-ji|Oh Jung-se", "romantic|tearjerker|thoughtful", "A psych-ward carer meets an antisocial children's author."],
  ["Weightlifting Fairy Kim Bok-joo", 2016, 8.3, 15, "s", "Comedy|Romance|Sport", "KR", "Oh Hyun-jong", "Lee Sung-kyung|Nam Joo-hyuk", "cozy|romantic|comingofage|feelgood", "A college weightlifter has her first crush."],
  ["What's Wrong with Secretary Kim", 2018, 8.0, 25, "s", "Comedy|Romance", "KR", "Park Joon-hwa", "Park Seo-joon|Park Min-young", "romantic|funny", "A narcissistic VP panics when his perfect secretary resigns."],
  ["Strong Woman Do Bong-soon", 2017, 8.1, 25, "s", "Action|Comedy|Fantasy|Romance", "KR", "Lee Hyung-min", "Park Bo-young|Park Hyung-sik|Ji Soo", "funny|romantic|feelgood", "A tiny woman with superhuman strength becomes a CEO's bodyguard."],
  ["Kingdom", 2019, 8.3, 70, "s", "Action|Drama|Horror", "KR", "Kim Seong-hun", "Ju Ji-hoon|Bae Doona|Ryu Seung-ryong", "scary|epic|tense", "A crown prince fights a plague of the undead in Joseon."],
  ["Move to Heaven", 2021, 8.6, 20, "s", "Drama", "KR", "Kim Sung-ho", "Lee Je-hoon|Tang Jun-sang", "tearjerker|feelgood", "A trauma cleaner and his uncle tell the last stories of the dead."],
  ["Moving", 2023, 8.4, 15, "s", "Action|Drama|Fantasy", "KR", "Park In-je", "Ryu Seung-ryong|Han Hyo-joo|Zo In-sung", "epic|actionpacked|family", "Teens with hidden powers and parents with secret pasts."],
  ["Our Beloved Summer", 2021, 8.0, 15, "s", "Comedy|Drama|Romance", "KR", "Kim Yoon-jin", "Choi Woo-shik|Kim Da-mi", "romantic|cozy|bittersweet", "Exes are forced to film a documentary together again."],
  ["When the Camellia Blooms", 2019, 8.3, 10, "s", "Comedy|Mystery|Romance", "KR", "Cha Young-hoon", "Gong Hyo-jin|Kang Ha-neul", "cozy|romantic|twisty", "A single mother and a lovestruck cop in a small town with a killer."],
  ["Sky Castle", 2018, 8.5, 10, "s", "Drama|Mystery", "KR", "Jo Hyun-tak", "Yum Jung-ah|Lee Tae-ran|Kim Seo-hyung", "dark|tense", "Wealthy mothers will do anything to get their kids into top schools."],
  ["True Beauty", 2020, 7.9, 20, "s", "Comedy|Drama|Romance", "KR", "Kim Sang-hyub", "Moon Ga-young|Cha Eun-woo|Hwang In-youp", "romantic|comingofage|funny", "A teen transforms herself with makeup and hides her bare face."],
  ["Love to Hate You", 2023, 7.4, 6, "s", "Comedy|Romance", "KR", "Kim Jung-kwon", "Kim Ok-vin|Teo Yoo", "funny|romantic", "A lawyer who distrusts men meets an actor who distrusts women."],
  ["King the Land", 2023, 7.3, 10, "s", "Comedy|Romance", "KR", "Im Hyun-wook", "Lee Jun-ho|Im Yoon-ah", "romantic|cozy", "A hotel heir who hates fake smiles meets a hotelier who's always smiling."],
  ["Healer", 2014, 8.4, 15, "s", "Action|Romance|Thriller", "KR", "Lee Jung-sub", "Ji Chang-wook|Park Min-young|Yoo Ji-tae", "actionpacked|romantic", "A night courier is drawn into a decades-old conspiracy."],
  ["Mouse", 2021, 8.3, 10, "s", "Crime|Thriller", "KR", "Choi Joon-bae", "Lee Seung-gi|Lee Hee-joon", "twisty|dark|tense", "A rookie cop and a detective hunt a psychopath killer."],
  ["Flower of Evil", 2020, 8.6, 15, "s", "Crime|Romance|Thriller", "KR", "Kim Cheol-gyu", "Lee Joon-gi|Moon Chae-won", "twisty|tense|romantic", "A detective begins to suspect her loving husband."],
  ["Alchemy of Souls", 2022, 8.6, 15, "s", "Action|Fantasy|Romance", "KR", "Park Joon-hwa", "Lee Jae-wook|Jung So-min|Go Youn-jung", "epic|romantic|actionpacked", "Young mages are entangled by a forbidden soul-shifting spell."],
  ["Hotel del Luna", 2019, 8.1, 15, "s", "Comedy|Fantasy|Romance", "KR", "Oh Choong-hwan", "IU|Yeo Jin-goo", "romantic|bittersweet", "A hotelier joins a hotel for ghosts run by a cursed woman."],
  ["Start-Up", 2020, 8.0, 20, "s", "Comedy|Drama|Romance", "KR", "Oh Choong-hwan", "Bae Suzy|Nam Joo-hyuk|Kim Seon-ho", "romantic|inspiring", "Young founders chase success in Korea's Silicon Valley."],
  ["Sweet Home", 2020, 7.3, 50, "s", "Action|Drama|Horror", "KR", "Lee Eung-bok", "Song Kang|Lee Jin-wook|Lee Si-young", "scary|actionpacked", "Apartment residents fight people turning into monsters."],
  ["All of Us Are Dead", 2022, 7.5, 70, "s", "Action|Drama|Horror", "KR", "Lee Jae-kyoo", "Park Ji-hoo|Yoon Chan-young|Cho Yi-hyun", "scary|tense|comingofage", "Students are trapped in their school during a zombie outbreak."],
  // ── C-dramas & Taiwan ────────────────────────────────────────────────────
  ["Hidden Love", 2023, 8.4, 10, "s", "Drama|Romance", "CN", "Li Mu", "Zhao Lusi|Chen Zheyuan", "romantic|cozy|comingofage", "A girl's secret crush on her brother's friend grows into love."],
  ["Love Between Fairy and Devil", 2022, 8.4, 12, "s", "Fantasy|Romance", "CN", "", "Dylan Wang|Esther Yu", "epic|romantic|funny", "A lowly fairy and a demon lord swap fates in a cursed bond."],
  ["When I Fly Towards You", 2023, 8.3, 6, "s", "Comedy|Romance", "CN", "", "Zhang Miaoyi|Zhou Yiran", "cozy|comingofage|romantic|feelgood", "A sunny transfer student melts the heart of a quiet classmate."],
  ["You Are My Glory", 2021, 8.0, 8, "s", "Romance", "CN", "", "Yang Yang|Dilraba Dilmurat", "romantic|cozy", "An actress reunites with her high-school crush, now an aerospace engineer."],
  ["Put Your Head on My Shoulder", 2019, 7.9, 8, "s", "Comedy|Romance", "CN", "", "Xing Fei|Lin Yi", "cozy|romantic|comingofage", "A college senior and a genius physics student fall for each other."],
  ["A Love So Beautiful", 2017, 8.1, 8, "s", "Comedy|Romance", "CN", "", "Hu Yitian|Shen Yue", "cozy|comingofage|romantic|nostalgic", "A bubbly girl chases her aloof neighbour through high school."],
  ["Go Ahead", 2020, 8.1, 5, "s", "Drama|Family", "CN", "", "Tan Songyun|Song Weilong|Zhang Xincheng", "tearjerker|family", "Three kids raised as siblings by two broken families."],
  ["Nirvana in Fire", 2015, 9.0, 10, "s", "Drama|History", "CN", "Kong Sheng", "Hu Ge|Liu Tao|Wang Kai", "epic|revenge|slowburn|twisty", "A disguised strategist returns to the capital to clear his family's name."],
  ["The Untamed", 2019, 8.8, 15, "s", "Action|Adventure|Fantasy", "CN", "", "Xiao Zhan|Wang Yibo", "epic|actionpacked|twisty", "Two cultivators unravel a mystery that spans lifetimes."],
  ["Story of Yanxi Palace", 2018, 8.1, 5, "s", "Drama|History|Romance", "CN", "Hui Kaidong", "Wu Jinyan|Qin Lan|Nie Yuan", "revenge|twisty", "A palace maid rises through the Forbidden City to avenge her sister."],
  ["Eternal Love", 2017, 8.1, 8, "s", "Fantasy|Romance", "CN", "", "Yang Mi|Mark Chao", "epic|romantic|tearjerker", "A goddess and a crown prince love across three lifetimes."],
  ["Till the End of the Moon", 2023, 8.0, 5, "s", "Fantasy|Romance", "CN", "", "Bai Lu|Luo Yunxi", "epic|romantic", "A disciple travels back 500 years to kill a devil god."],
  ["Love Like the Galaxy", 2022, 8.1, 5, "s", "Drama|History|Romance", "CN", "", "Zhao Lusi|Wu Lei", "epic|romantic", "A neglected daughter wins the heart of a general."],
  ["The Longest Day in Chang'an", 2019, 8.4, 4, "s", "Action|History|Thriller", "CN", "Cao Dun", "Lei Jiayin|Jackson Yee", "tense|epic", "A death-row prisoner has 24 hours to save the Tang capital."],
  ["Joy of Life", 2019, 8.4, 5, "s", "Action|Comedy|Fantasy", "CN", "", "Zhang Ruoyun|Li Qin", "funny|epic|twisty", "A modern man reborn in an ancient kingdom navigates palace intrigue."],
  ["Reset", 2022, 8.0, 4, "s", "Mystery|Sci-Fi|Thriller", "CN", "", "Bai Jingting|Zhao Jinmai", "mindbending|tense", "Two passengers relive the same bus explosion and try to stop it."],
  ["Someday or One Day", 2019, 8.6, 10, "s", "Drama|Fantasy|Mystery", "TW", "", "Alice Ko|Greg Hsu|Patrick Shih", "mindbending|romantic|bittersweet", "A grieving woman wakes up in 1998 in a stranger's body."],
];

const slug = (s: string) =>
  s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

export const catalog: Title[] = rows.map(
  ([
    title,
    year,
    rating,
    votes,
    kind,
    genres,
    country,
    director,
    cast,
    tags,
    blurb,
  ]) => ({
    id: `${slug(title)}-${year}`,
    title,
    year,
    rating,
    votes,
    kind: kind === "m" ? "movie" : "series",
    genres: genres.split("|"),
    country,
    director,
    cast: cast ? cast.split("|") : [],
    tags: tags.split("|"),
    blurb,
  }),
);
